/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['.profile[_ngcontent-%COMP%] {\n  overflow: hidden;\n}\n\n.profile-avatar[_ngcontent-%COMP%] {\n  width: 50px;\n  height: 50px;\n  border-radius: 50%;\n  float: left;\n}\n\n.profile-name[_ngcontent-%COMP%] {\n  float: left;\n  padding-left: 10px;\n}\n\n.profile-name[_ngcontent-%COMP%]   p[_ngcontent-%COMP%] {\n  font-size: 18px;\n  margin: 0;\n  line-height: 50px;\n}\n\n.profile-logout[_ngcontent-%COMP%] {\n  margin-left: 5px;\n  font-size: 14px;\n  cursor: pointer;\n  color: #aaaaaa;\n}'];