/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['h2[_ngcontent-%COMP%] {\n    color: #3e539c;\n}\ndiv[_ngcontent-%COMP%] {\n    font-size: 16px;\n}\n.text[_ngcontent-%COMP%] {\n  margin-bottom: 3em;\n}'];