/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../../components/post/post.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '@angular/router/src/router';
import * as import9 from '@angular/router/src/router_state';
import * as import10 from '../../../../../services/http.service';
import * as import11 from './post.component.scss.shim.ngstyle';
import * as import12 from '@angular/core/src/animation/animation_transition';
import * as import13 from '@angular/core/src/animation/animation_sequence_player';
import * as import14 from '@angular/core/src/animation/animation_styles';
import * as import15 from '@angular/core/src/animation/animation_style_util';
import * as import16 from '@angular/core/src/animation/animation_keyframe';
import * as import17 from '@angular/core/src/animation/animation_player';
import * as import18 from '../../../../../components/controls/controls.component';
import * as import19 from '../controls/controls.component.ngfactory';
import * as import20 from '@angular/core/src/linker/view_container';
import * as import21 from '../../../../../components/comments/comments.component';
import * as import22 from '../comments/comments.component.ngfactory';
import * as import23 from '@angular/core/src/change_detection/change_detection_util';
import * as import24 from '../../../../../services/auth.service';
import * as import25 from '../../../../../services/comments.service';
import * as import26 from '@angular/core/src/security';
import * as import27 from '../../../../../components/auth/auth-profile.component';
import * as import28 from '../auth/auth-profile.component.ngfactory';
import * as import29 from '../../../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import30 from '../../../../../pipes/markdown.pipe';
import * as import31 from '../../../../../pipes/safe-html.pipe';
import * as import32 from '@angular/common/src/location/location';
import * as import33 from '../../../../../services/user.service';
import * as import34 from '@angular/core/src/linker/template_ref';
import * as import35 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import36 from '@angular/common/src/directives/ng_if';
export class Wrapper_PostComponent {
  /*private*/ _eventHandler:Function;
  context:import0.PostComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any,p2:any) {
    this._changed = false;
    this.context = new import0.PostComponent(p0,p1,p2);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_PostComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_PostComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.PostComponent>;
  _PostComponent_0_3:Wrapper_PostComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_PostComponent_Host0,renderType_PostComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'post',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_PostComponent0(this.viewUtils,this,0,this._el_0);
    this._PostComponent_0_3 = new Wrapper_PostComponent(this.injectorGet(import8.Router,this.parentIndex),this.injectorGet(import9.ActivatedRoute,this.parentIndex),this.injectorGet(import10.HttpService,this.parentIndex));
    this.compView_0.create(this._PostComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._PostComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.PostComponent) && (0 === requestNodeIndex))) { return this._PostComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._PostComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const PostComponentNgFactory:import7.ComponentFactory<import0.PostComponent> = new import7.ComponentFactory<import0.PostComponent>('post',View_PostComponent_Host0,import0.PostComponent);
const styles_PostComponent:any[] = [import11.styles];
var PostComponent_post_states:any = {
  'in': {'opacity': '1'},
  '*': {},
  'void': {}
}
;
function PostComponent_post_factory(view:import1.AppView<any>,element:any,currentState:any,nextState:any):import12.AnimationTransition {
  var previousPlayers:any = view.animationContext.getAnimationPlayers(element,((nextState == 'void')? (null as any): 'post'));
  var collectedStyles:any = {};
  var player:any = (null as any);
  var totalTime:any = 0;
  var defaultStateStyles:any = PostComponent_post_states['*'];
  var startStateStyles:any = PostComponent_post_states[currentState];
  if ((startStateStyles == (null as any))) { (startStateStyles = defaultStateStyles); }
  var endStateStyles:any = PostComponent_post_states[nextState];
  if ((endStateStyles == (null as any))) { (endStateStyles = defaultStateStyles); }
  if (((player == (null as any)) && ((currentState == 'void') && true))) {
      player = new import13.AnimationSequencePlayer([view.renderer.animate(element,new import14.AnimationStyles(import15.collectAndResolveStyles(collectedStyles,[
        startStateStyles,
        {'opacity': '0'}
      ]
      )),import15.balanceAnimationKeyframes(collectedStyles,endStateStyles,[
        new import16.AnimationKeyframe(0,new import14.AnimationStyles(import15.collectAndResolveStyles(collectedStyles,[{}]))),
        new import16.AnimationKeyframe(1,new import14.AnimationStyles(import15.collectAndResolveStyles(collectedStyles,[{}])))
      ]
    ),200,0,(null as any),previousPlayers)]);
    totalTime = 200;
  }
  if (((player == (null as any)) && (true && (nextState == 'void')))) {
      player = new import13.AnimationSequencePlayer([view.renderer.animate(element,new import14.AnimationStyles(import15.collectAndResolveStyles(collectedStyles,[startStateStyles])),[
        new import16.AnimationKeyframe(0,new import14.AnimationStyles(import15.collectAndResolveStyles(collectedStyles,[{'opacity': 'true'}]))),
        new import16.AnimationKeyframe(1,new import14.AnimationStyles(import15.collectAndResolveStyles(collectedStyles,[{'opacity': '0'}])))
      ]
    ,300,0,(null as any),previousPlayers)]);
    totalTime = 300;
  }
  if ((player == (null as any))) { (player = new import17.NoOpAnimationPlayer()); }
  player.onDone(():void => {
    player.destroy();
    import15.renderStyles(element,view.renderer,import15.prepareFinalAnimationStyles(startStateStyles,endStateStyles));
  });
  new import13.AnimationSequencePlayer(previousPlayers).destroy();
  import15.renderStyles(element,view.renderer,import15.clearStyles(startStateStyles));
  view.animationContext.queueAnimation(element,'post',player);
  return new import12.AnimationTransition(player,currentState,nextState,totalTime);
}
class View_PostComponent1 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import18.ControlsComponent>;
  _ControlsComponent_0_3:import19.Wrapper_ControlsComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import20.ViewContainer) {
    super(View_PostComponent1,renderType_PostComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'controls',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_0 = new import19.View_ControlsComponent0(this.viewUtils,this,0,this._el_0);
    this._ControlsComponent_0_3 = new import19.Wrapper_ControlsComponent(this.parentView.injectorGet(import8.Router,this.parentIndex),this.parentView.injectorGet(import9.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import10.HttpService,this.parentIndex));
    this.compView_0.create(this._ControlsComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import18.ControlsComponent) && (0 === requestNodeIndex))) { return this._ControlsComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = this.parentView.context.post;
    this._ControlsComponent_0_3.check_post(currVal_0_0_0,throwOnChange,false);
    this._ControlsComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_PostComponent2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  compView_10:import1.AppView<import21.CommentsComponent>;
  _CommentsComponent_10_3:import22.Wrapper_CommentsComponent;
  _text_11:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  _pipe_markdown_0_0:any;
  _pipe_safeHtml_1_0:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import20.ViewContainer) {
    super(View_PostComponent2,renderType_PostComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_14 = import23.UNINITIALIZED;
    this._expr_15 = import23.UNINITIALIZED;
    this._expr_16 = import23.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'section',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'h2',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','text'),(null as any));
    this._text_6 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_0,'button',new import3.InlineArray4(4,'class','btn btn-primary','type','button'),(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'Go back',(null as any));
    this._text_9 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_0,'comments',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_10 = new import22.View_CommentsComponent0(this.viewUtils,this,10,this._el_10);
    this._CommentsComponent_10_3 = new import22.Wrapper_CommentsComponent(this.parentView.injectorGet(import9.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import24.AuthService,this.parentIndex),this.parentView.injectorGet(import25.CommentsService,this.parentIndex));
    this.compView_10.create(this._CommentsComponent_10_3.context);
    this._text_11 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._pipe_markdown_0_0 = import3.pureProxy1((<View_PostComponent0>this.parentView)._pipe_markdown_0.transform.bind((<View_PostComponent0>this.parentView)._pipe_markdown_0));
    this._pipe_safeHtml_1_0 = import3.pureProxy1((<View_PostComponent0>this.parentView)._pipe_safeHtml_1.transform.bind((<View_PostComponent0>this.parentView)._pipe_safeHtml_1));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_7,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_7));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import21.CommentsComponent) && (10 === requestNodeIndex))) { return this._CommentsComponent_10_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import23.ValueUnwrapper();
    const currVal_14:any = this.parentView.context.post.state;
    if (import3.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      var animationTransition_post:any = this.componentType.animations['post'](this,this._el_0,((this._expr_14 == import23.UNINITIALIZED)? 'void': this._expr_14),((currVal_14 == import23.UNINITIALIZED)? 'void': currVal_14));
      this._expr_14 = currVal_14;
    }
    const currVal_10_0_0:any = this.parentView.context.post.id;
    this._CommentsComponent_10_3.check_postId(currVal_10_0_0,throwOnChange,false);
    const currVal_10_0_1:any = (<View_PostComponent0>this.parentView)._AuthProfileComponent_0_3.context.logged;
    this._CommentsComponent_10_3.check_logged(currVal_10_0_1,throwOnChange,false);
    this._CommentsComponent_10_3.ngDoCheck(this,this._el_10,throwOnChange);
    const currVal_15:any = import3.inlineInterpolate(1,'',this.parentView.context.post.title,'');
    if (import3.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setText(this._text_3,currVal_15);
      this._expr_15 = currVal_15;
    }
    valUnwrapper.reset();
    const currVal_16:any = valUnwrapper.unwrap(import3.castByValue(this._pipe_safeHtml_1_0,(<View_PostComponent0>this.parentView)._pipe_safeHtml_1.transform)(valUnwrapper.unwrap(import3.castByValue(this._pipe_markdown_0_0,(<View_PostComponent0>this.parentView)._pipe_markdown_0.transform)(this.parentView.context.post.text_full_strings))));
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_16,currVal_16))) {
      this.renderer.setElementProperty(this._el_5,'innerHTML',this.viewUtils.sanitizer.sanitize(import26.SecurityContext.HTML,currVal_16));
      this._expr_16 = currVal_16;
    }
    this.compView_10.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_10.destroy();
  }
  detachInternal():void {
    var animationTransition_post:any = this.componentType.animations['post'](this,this._el_0,this._expr_14,'void');
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_7(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.goBack()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
var renderType_PostComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.Emulated,styles_PostComponent,{'post': PostComponent_post_factory});
export class View_PostComponent0 extends import1.AppView<import0.PostComponent> {
  _el_0:any;
  compView_0:import1.AppView<import27.AuthProfileComponent>;
  _AuthProfileComponent_0_3:import28.Wrapper_AuthProfileComponent;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _vc_2:import20.ViewContainer;
  _TemplateRef_2_5:any;
  _NgIf_2_6:import29.Wrapper_NgIf;
  _text_3:any;
  _anchor_4:any;
  /*private*/ _vc_4:import20.ViewContainer;
  _TemplateRef_4_5:any;
  _NgIf_4_6:import29.Wrapper_NgIf;
  _text_5:any;
  _pipe_markdown_0:import30.MarkdownPipe;
  _pipe_safeHtml_1:import31.SafeHtmlPipe;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_PostComponent0,renderType_PostComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'auth-profile',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_0 = new import28.View_AuthProfileComponent0(this.viewUtils,this,0,this._el_0);
    this._AuthProfileComponent_0_3 = new import28.Wrapper_AuthProfileComponent(this.parentView.injectorGet(import8.Router,this.parentIndex),this.parentView.injectorGet(import9.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import32.Location,this.parentIndex),this.parentView.injectorGet(import24.AuthService,this.parentIndex),this.parentView.injectorGet(import33.UserService,this.parentIndex));
    this.compView_0.create(this._AuthProfileComponent_0_3.context);
    this._text_1 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._vc_2 = new import20.ViewContainer(2,(null as any),this,this._anchor_2);
    this._TemplateRef_2_5 = new import34.TemplateRef_(this,2,this._anchor_2);
    this._NgIf_2_6 = new import29.Wrapper_NgIf(this._vc_2.vcRef,this._TemplateRef_2_5);
    this._text_3 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._anchor_4 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._vc_4 = new import20.ViewContainer(4,(null as any),this,this._anchor_4);
    this._TemplateRef_4_5 = new import34.TemplateRef_(this,4,this._anchor_4);
    this._NgIf_4_6 = new import29.Wrapper_NgIf(this._vc_4.vcRef,this._TemplateRef_4_5);
    this._text_5 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._pipe_markdown_0 = new import30.MarkdownPipe();
    this._pipe_safeHtml_1 = new import31.SafeHtmlPipe(this.parentView.injectorGet(import35.DomSanitizer,this.parentIndex));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3,
      this._anchor_4,
      this._text_5
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import27.AuthProfileComponent) && (0 === requestNodeIndex))) { return this._AuthProfileComponent_0_3.context; }
    if (((token === import34.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import36.NgIf) && (2 === requestNodeIndex))) { return this._NgIf_2_6.context; }
    if (((token === import34.TemplateRef) && (4 === requestNodeIndex))) { return this._TemplateRef_4_5; }
    if (((token === import36.NgIf) && (4 === requestNodeIndex))) { return this._NgIf_4_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._AuthProfileComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    const currVal_2_0_0:any = this._AuthProfileComponent_0_3.context.canEdit;
    this._NgIf_2_6.check_ngIf(currVal_2_0_0,throwOnChange,false);
    this._NgIf_2_6.ngDoCheck(this,this._anchor_2,throwOnChange);
    const currVal_4_0_0:any = this.context.post;
    this._NgIf_4_6.check_ngIf(currVal_4_0_0,throwOnChange,false);
    this._NgIf_4_6.ngDoCheck(this,this._anchor_4,throwOnChange);
    this._vc_2.detectChangesInNestedViews(throwOnChange);
    this._vc_4.detectChangesInNestedViews(throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this._vc_2.destroyNestedViews();
    this._vc_4.destroyNestedViews();
    this.compView_0.destroy();
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 2)) { return new View_PostComponent1(this.viewUtils,this,2,this._anchor_2,this._vc_2); }
    if ((nodeIndex == 4)) { return new View_PostComponent2(this.viewUtils,this,4,this._anchor_4,this._vc_4); }
    return (null as any);
  }
}