/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['.wrap[_ngcontent-%COMP%] {\n  min-height: 3em;\n  margin-top: 1em;\n}\n.own-blogs[_ngcontent-%COMP%] {\n  float: right;\n  text-align: right;\n}'];