/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../../components/start/start.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '@angular/router/src/router';
import * as import9 from './start.component.scss.shim.ngstyle';
import * as import10 from '@angular/core/src/animation/animation_transition';
import * as import11 from '@angular/core/src/animation/animation_sequence_player';
import * as import12 from '@angular/core/src/animation/animation_styles';
import * as import13 from '@angular/core/src/animation/animation_style_util';
import * as import14 from '@angular/core/src/animation/animation_keyframe';
import * as import15 from '@angular/core/src/animation/animation_player';
import * as import16 from '@angular/core/src/linker/view_container';
import * as import17 from '../../../../../components/auth/auth-profile.component';
import * as import18 from '../auth/auth-profile.component.ngfactory';
import * as import19 from '../../../../node_modules/@angular/forms/src/directives/ng_form.ngfactory';
import * as import20 from '../../../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import21 from '../../../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import22 from '@angular/core/src/change_detection/change_detection_util';
import * as import23 from '@angular/router/src/router_state';
import * as import24 from '@angular/common/src/location/location';
import * as import25 from '../../../../../services/auth.service';
import * as import26 from '../../../../../services/user.service';
import * as import27 from '@angular/core/src/linker/template_ref';
import * as import28 from '@angular/common/src/directives/ng_if';
import * as import29 from '@angular/forms/src/directives/ng_form';
import * as import30 from '@angular/forms/src/directives/control_container';
import * as import31 from '@angular/forms/src/directives/ng_control_status';
export class Wrapper_StartComponent {
  /*private*/ _eventHandler:Function;
  context:import0.StartComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any) {
    this._changed = false;
    this.context = new import0.StartComponent(p0);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_StartComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_StartComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.StartComponent>;
  _StartComponent_0_3:Wrapper_StartComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_StartComponent_Host0,renderType_StartComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'start',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_StartComponent0(this.viewUtils,this,0,this._el_0);
    this._StartComponent_0_3 = new Wrapper_StartComponent(this.injectorGet(import8.Router,this.parentIndex));
    this.compView_0.create(this._StartComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._StartComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.StartComponent) && (0 === requestNodeIndex))) { return this._StartComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._StartComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const StartComponentNgFactory:import7.ComponentFactory<import0.StartComponent> = new import7.ComponentFactory<import0.StartComponent>('start',View_StartComponent_Host0,import0.StartComponent);
const styles_StartComponent:any[] = [import9.styles];
var StartComponent_start_states:any = {
  'in': {'opacity': '1'},
  '*': {},
  'void': {}
}
;
function StartComponent_start_factory(view:import1.AppView<any>,element:any,currentState:any,nextState:any):import10.AnimationTransition {
  var previousPlayers:any = view.animationContext.getAnimationPlayers(element,((nextState == 'void')? (null as any): 'start'));
  var collectedStyles:any = {};
  var player:any = (null as any);
  var totalTime:any = 0;
  var defaultStateStyles:any = StartComponent_start_states['*'];
  var startStateStyles:any = StartComponent_start_states[currentState];
  if ((startStateStyles == (null as any))) { (startStateStyles = defaultStateStyles); }
  var endStateStyles:any = StartComponent_start_states[nextState];
  if ((endStateStyles == (null as any))) { (endStateStyles = defaultStateStyles); }
  if (((player == (null as any)) && ((currentState == 'void') && true))) {
      player = new import11.AnimationSequencePlayer([view.renderer.animate(element,new import12.AnimationStyles(import13.collectAndResolveStyles(collectedStyles,[
        startStateStyles,
        {'opacity': '0'}
      ]
      )),import13.balanceAnimationKeyframes(collectedStyles,endStateStyles,[
        new import14.AnimationKeyframe(0,new import12.AnimationStyles(import13.collectAndResolveStyles(collectedStyles,[{}]))),
        new import14.AnimationKeyframe(1,new import12.AnimationStyles(import13.collectAndResolveStyles(collectedStyles,[{}])))
      ]
    ),200,0,(null as any),previousPlayers)]);
    totalTime = 200;
  }
  if (((player == (null as any)) && (true && (nextState == 'void')))) {
      player = new import11.AnimationSequencePlayer([view.renderer.animate(element,new import12.AnimationStyles(import13.collectAndResolveStyles(collectedStyles,[startStateStyles])),[
        new import14.AnimationKeyframe(0,new import12.AnimationStyles(import13.collectAndResolveStyles(collectedStyles,[{'opacity': 'true'}]))),
        new import14.AnimationKeyframe(1,new import12.AnimationStyles(import13.collectAndResolveStyles(collectedStyles,[{'opacity': '0'}])))
      ]
    ,100,0,(null as any),previousPlayers)]);
    totalTime = 100;
  }
  if ((player == (null as any))) { (player = new import15.NoOpAnimationPlayer()); }
  player.onDone(():void => {
    player.destroy();
    import13.renderStyles(element,view.renderer,import13.prepareFinalAnimationStyles(startStateStyles,endStateStyles));
  });
  new import11.AnimationSequencePlayer(previousPlayers).destroy();
  import13.renderStyles(element,view.renderer,import13.clearStyles(startStateStyles));
  view.animationContext.queueAnimation(element,'start',player);
  return new import10.AnimationTransition(player,currentState,nextState,totalTime);
}
class View_StartComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import16.ViewContainer) {
    super(View_StartComponent1,renderType_StartComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'Необходима авторизация',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
var renderType_StartComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.Emulated,styles_StartComponent,{'start': StartComponent_start_factory});
export class View_StartComponent0 extends import1.AppView<import0.StartComponent> {
  _el_0:any;
  compView_0:import1.AppView<import17.AuthProfileComponent>;
  _AuthProfileComponent_0_3:import18.Wrapper_AuthProfileComponent;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _el_7:any;
  _text_8:any;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  _text_23:any;
  _text_24:any;
  _text_25:any;
  _el_26:any;
  _NgForm_26_3:import19.Wrapper_NgForm;
  _ControlContainer_26_4:any;
  _NgControlStatusGroup_26_5:import20.Wrapper_NgControlStatusGroup;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _text_32:any;
  _anchor_33:any;
  /*private*/ _vc_33:import16.ViewContainer;
  _TemplateRef_33_5:any;
  _NgIf_33_6:import21.Wrapper_NgIf;
  _text_34:any;
  _text_35:any;
  _el_36:any;
  _text_37:any;
  _el_38:any;
  _text_39:any;
  _text_40:any;
  _el_41:any;
  _text_42:any;
  _el_43:any;
  _text_44:any;
  _el_45:any;
  _text_46:any;
  _el_47:any;
  _el_48:any;
  _text_49:any;
  _text_50:any;
  _text_51:any;
  _el_52:any;
  _text_53:any;
  _el_54:any;
  _text_55:any;
  _el_56:any;
  _text_57:any;
  _el_58:any;
  _text_59:any;
  _el_60:any;
  _text_61:any;
  _el_62:any;
  _text_63:any;
  _text_64:any;
  _text_65:any;
  _el_66:any;
  _text_67:any;
  _el_68:any;
  _text_69:any;
  _text_70:any;
  _el_71:any;
  _text_72:any;
  _text_73:any;
  _el_74:any;
  _text_75:any;
  _el_76:any;
  _text_77:any;
  _text_78:any;
  _text_79:any;
  _text_80:any;
  _text_81:any;
  _text_82:any;
  _el_83:any;
  _text_84:any;
  _el_85:any;
  _text_86:any;
  _el_87:any;
  _el_88:any;
  _text_89:any;
  _text_90:any;
  _text_91:any;
  _el_92:any;
  _text_93:any;
  _el_94:any;
  _text_95:any;
  _el_96:any;
  _text_97:any;
  _el_98:any;
  _text_99:any;
  _el_100:any;
  _text_101:any;
  _text_102:any;
  _el_103:any;
  _text_104:any;
  _el_105:any;
  _text_106:any;
  _el_107:any;
  _text_108:any;
  _el_109:any;
  _text_110:any;
  _el_111:any;
  _text_112:any;
  _text_113:any;
  _el_114:any;
  _text_115:any;
  _text_116:any;
  _el_117:any;
  _text_118:any;
  _text_119:any;
  _el_120:any;
  _text_121:any;
  _text_122:any;
  _el_123:any;
  _text_124:any;
  _text_125:any;
  _el_126:any;
  _text_127:any;
  _text_128:any;
  _el_129:any;
  _text_130:any;
  _text_131:any;
  _text_132:any;
  _text_133:any;
  _el_134:any;
  _text_135:any;
  _text_136:any;
  _text_137:any;
  _text_138:any;
  _text_139:any;
  _text_140:any;
  _el_141:any;
  _text_142:any;
  _el_143:any;
  _text_144:any;
  _el_145:any;
  _el_146:any;
  _text_147:any;
  _text_148:any;
  _text_149:any;
  _el_150:any;
  _text_151:any;
  _el_152:any;
  _text_153:any;
  _el_154:any;
  _text_155:any;
  _text_156:any;
  _text_157:any;
  _text_158:any;
  _text_159:any;
  _text_160:any;
  /*private*/ _expr_169:any;
  /*private*/ _expr_170:any;
  /*private*/ _expr_171:any;
  /*private*/ _expr_172:any;
  /*private*/ _expr_173:any;
  /*private*/ _expr_174:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_StartComponent0,renderType_StartComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
    this._expr_169 = import22.UNINITIALIZED;
    this._expr_170 = import22.UNINITIALIZED;
    this._expr_171 = import22.UNINITIALIZED;
    this._expr_172 = import22.UNINITIALIZED;
    this._expr_173 = import22.UNINITIALIZED;
    this._expr_174 = import22.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'auth-profile',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_0 = new import18.View_AuthProfileComponent0(this.viewUtils,this,0,this._el_0);
    this._AuthProfileComponent_0_3 = new import18.Wrapper_AuthProfileComponent(this.parentView.injectorGet(import8.Router,this.parentIndex),this.parentView.injectorGet(import23.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import24.Location,this.parentIndex),this.parentView.injectorGet(import25.AuthService,this.parentIndex),this.parentView.injectorGet(import26.UserService,this.parentIndex));
    this.compView_0.create(this._AuthProfileComponent_0_3.context);
    this._text_1 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,parentRenderNode,'section',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n\n    ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'h4',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n        Для того, что-бы начать пользоваться платформой ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_4,'b',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_6,'i',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'itworks',(null as any));
    this._text_9 = this.renderer.createText(this._el_4,', достатачно\n    ',(null as any));
    this._text_10 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,this._el_2,'ul',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'\n        ',(null as any));
    this._el_13 = import3.createRenderElement(this.renderer,this._el_11,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_14 = this.renderer.createText(this._el_13,'быть пользователем GitHub',(null as any));
    this._text_15 = this.renderer.createText(this._el_11,'\n        ',(null as any));
    this._el_16 = import3.createRenderElement(this.renderer,this._el_11,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'создать репозиторий на GitHub',(null as any));
    this._text_18 = this.renderer.createText(this._el_11,'\n        ',(null as any));
    this._el_19 = import3.createRenderElement(this.renderer,this._el_11,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_20 = this.renderer.createText(this._el_19,'авторизироваться на платформе',(null as any));
    this._text_21 = this.renderer.createText(this._el_11,'\n        ',(null as any));
    this._el_22 = import3.createRenderElement(this.renderer,this._el_11,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_23 = this.renderer.createText(this._el_22,'активировать блог (ввести имя созданного репозитория в форму)',(null as any));
    this._text_24 = this.renderer.createText(this._el_11,'\n    ',(null as any));
    this._text_25 = this.renderer.createText(this._el_2,'\n\n    ',(null as any));
    this._el_26 = import3.createRenderElement(this.renderer,this._el_2,'form',new import3.InlineArray2(2,'class','form-inline'),(null as any));
    this._NgForm_26_3 = new import19.Wrapper_NgForm((null as any),(null as any));
    this._ControlContainer_26_4 = this._NgForm_26_3.context;
    this._NgControlStatusGroup_26_5 = new import20.Wrapper_NgControlStatusGroup(this._ControlContainer_26_4);
    this._text_27 = this.renderer.createText(this._el_26,'\n        ',(null as any));
    this._el_28 = import3.createRenderElement(this.renderer,this._el_26,'input',new import3.InlineArray8(8,'class','form-control','placeholder','Repository name','required','','type','text'),(null as any));
    this._text_29 = this.renderer.createText(this._el_26,'\n        ',(null as any));
    this._el_30 = import3.createRenderElement(this.renderer,this._el_26,'button',new import3.InlineArray4(4,'class','btn btn-primary','type','submit'),(null as any));
    this._text_31 = this.renderer.createText(this._el_30,'Activate Blog',(null as any));
    this._text_32 = this.renderer.createText(this._el_26,'\n        ',(null as any));
    this._anchor_33 = this.renderer.createTemplateAnchor(this._el_26,(null as any));
    this._vc_33 = new import16.ViewContainer(33,26,this,this._anchor_33);
    this._TemplateRef_33_5 = new import27.TemplateRef_(this,33,this._anchor_33);
    this._NgIf_33_6 = new import21.Wrapper_NgIf(this._vc_33.vcRef,this._TemplateRef_33_5);
    this._text_34 = this.renderer.createText(this._el_26,'\n    ',(null as any));
    this._text_35 = this.renderer.createText(this._el_2,'\n\n    ',(null as any));
    this._el_36 = import3.createRenderElement(this.renderer,this._el_2,'hr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_37 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_38 = import3.createRenderElement(this.renderer,this._el_2,'p',new import3.InlineArray2(2,'class','alert alert-info'),(null as any));
    this._text_39 = this.renderer.createText(this._el_38,'\n        Для корректной работы блога, все изменения необходимо производить через интерфейс платформы\n    ',(null as any));
    this._text_40 = this.renderer.createText(this._el_2,'\n\n    ',(null as any));
    this._el_41 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray4(4,'class','panel-group','id','accordion1'),(null as any));
    this._text_42 = this.renderer.createText(this._el_41,'\n\n        ',(null as any));
    this._el_43 = import3.createRenderElement(this.renderer,this._el_41,'div',new import3.InlineArray2(2,'class','panel panel-default'),(null as any));
    this._text_44 = this.renderer.createText(this._el_43,'\n            ',(null as any));
    this._el_45 = import3.createRenderElement(this.renderer,this._el_43,'div',new import3.InlineArray2(2,'class','panel-heading'),(null as any));
    this._text_46 = this.renderer.createText(this._el_45,'\n                ',(null as any));
    this._el_47 = import3.createRenderElement(this.renderer,this._el_45,'h4',new import3.InlineArray2(2,'class','panel-title'),(null as any));
    this._el_48 = import3.createRenderElement(this.renderer,this._el_47,'a',new import3.InlineArray4(4,'data-parent','#accordion1','data-toggle','collapse'),(null as any));
    this._text_49 = this.renderer.createText(this._el_48,'\n                    Как вести вести блог нескольким людям\n                ',(null as any));
    this._text_50 = this.renderer.createText(this._el_45,'\n            ',(null as any));
    this._text_51 = this.renderer.createText(this._el_43,'\n            ',(null as any));
    this._el_52 = import3.createRenderElement(this.renderer,this._el_43,'div',new import3.InlineArray2(2,'class','panel-collapse collapse'),(null as any));
    this._text_53 = this.renderer.createText(this._el_52,'\n                ',(null as any));
    this._el_54 = import3.createRenderElement(this.renderer,this._el_52,'div',new import3.InlineArray2(2,'class','panel-body'),(null as any));
    this._text_55 = this.renderer.createText(this._el_54,'\n                    Чтобы блог могли вести одновременно несколько человек, то необходимо:\n                    ',(null as any));
    this._el_56 = import3.createRenderElement(this.renderer,this._el_54,'hr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_57 = this.renderer.createText(this._el_54,'\n                    ',(null as any));
    this._el_58 = import3.createRenderElement(this.renderer,this._el_54,'ul',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_59 = this.renderer.createText(this._el_58,'\n\n                        ',(null as any));
    this._el_60 = import3.createRenderElement(this.renderer,this._el_58,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_61 = this.renderer.createText(this._el_60,'в своем репозитории зайти в настройки (',(null as any));
    this._el_62 = import3.createRenderElement(this.renderer,this._el_60,'code',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_63 = this.renderer.createText(this._el_62,'Settings',(null as any));
    this._text_64 = this.renderer.createText(this._el_60,')',(null as any));
    this._text_65 = this.renderer.createText(this._el_58,'\n                        ',(null as any));
    this._el_66 = import3.createRenderElement(this.renderer,this._el_58,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_67 = this.renderer.createText(this._el_66,'выбрать пункт ',(null as any));
    this._el_68 = import3.createRenderElement(this.renderer,this._el_66,'code',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_69 = this.renderer.createText(this._el_68,'Collaborators',(null as any));
    this._text_70 = this.renderer.createText(this._el_58,'\n                        ',(null as any));
    this._el_71 = import3.createRenderElement(this.renderer,this._el_58,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_72 = this.renderer.createText(this._el_71,'в поле ввести имя пользователя, которому предоставляется доступ',(null as any));
    this._text_73 = this.renderer.createText(this._el_58,'\n                        ',(null as any));
    this._el_74 = import3.createRenderElement(this.renderer,this._el_58,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_75 = this.renderer.createText(this._el_74,'нажать кнопку ',(null as any));
    this._el_76 = import3.createRenderElement(this.renderer,this._el_74,'code',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_77 = this.renderer.createText(this._el_76,'Add collaborator',(null as any));
    this._text_78 = this.renderer.createText(this._el_58,'\n                    ',(null as any));
    this._text_79 = this.renderer.createText(this._el_54,'\n                ',(null as any));
    this._text_80 = this.renderer.createText(this._el_52,'\n            ',(null as any));
    this._text_81 = this.renderer.createText(this._el_43,'\n        ',(null as any));
    this._text_82 = this.renderer.createText(this._el_41,'\n\n        ',(null as any));
    this._el_83 = import3.createRenderElement(this.renderer,this._el_41,'div',new import3.InlineArray2(2,'class','panel panel-default'),(null as any));
    this._text_84 = this.renderer.createText(this._el_83,'\n            ',(null as any));
    this._el_85 = import3.createRenderElement(this.renderer,this._el_83,'div',new import3.InlineArray2(2,'class','panel-heading'),(null as any));
    this._text_86 = this.renderer.createText(this._el_85,'\n                ',(null as any));
    this._el_87 = import3.createRenderElement(this.renderer,this._el_85,'h4',new import3.InlineArray2(2,'class','panel-title'),(null as any));
    this._el_88 = import3.createRenderElement(this.renderer,this._el_87,'a',new import3.InlineArray4(4,'data-parent','#accordion1','data-toggle','collapse'),(null as any));
    this._text_89 = this.renderer.createText(this._el_88,'\n                    Проблемы с обновлением блога\n                ',(null as any));
    this._text_90 = this.renderer.createText(this._el_85,'\n            ',(null as any));
    this._text_91 = this.renderer.createText(this._el_83,'\n            ',(null as any));
    this._el_92 = import3.createRenderElement(this.renderer,this._el_83,'div',new import3.InlineArray2(2,'class','panel-collapse collapse'),(null as any));
    this._text_93 = this.renderer.createText(this._el_92,'\n                ',(null as any));
    this._el_94 = import3.createRenderElement(this.renderer,this._el_92,'div',new import3.InlineArray2(2,'class','panel-body'),(null as any));
    this._text_95 = this.renderer.createText(this._el_94,'\n                    Скорее всего Вы работаете с блогом минуя платформу. ',(null as any));
    this._el_96 = import3.createRenderElement(this.renderer,this._el_94,'br',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_97 = this.renderer.createText(this._el_94,' Для корректной работы блога, все изменения необходимо производить через интерфейс платформы ',(null as any));
    this._el_98 = import3.createRenderElement(this.renderer,this._el_94,'br',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_99 = this.renderer.createText(this._el_94,' Если у вас есть непреодолимое желание использовать интерфейс GitHub или ',(null as any));
    this._el_100 = import3.createRenderElement(this.renderer,this._el_94,'code',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_101 = this.renderer.createText(this._el_100,'git push',(null as any));
    this._text_102 = this.renderer.createText(this._el_94,',\n                    тогда необходимо:\n                    ',(null as any));
    this._el_103 = import3.createRenderElement(this.renderer,this._el_94,'hr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_104 = this.renderer.createText(this._el_94,'\n                    ',(null as any));
    this._el_105 = import3.createRenderElement(this.renderer,this._el_94,'ul',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_106 = this.renderer.createText(this._el_105,'\n                        ',(null as any));
    this._el_107 = import3.createRenderElement(this.renderer,this._el_105,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_108 = this.renderer.createText(this._el_107,'или настроить webhook:\n                            ',(null as any));
    this._el_109 = import3.createRenderElement(this.renderer,this._el_107,'ul',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_110 = this.renderer.createText(this._el_109,'\n\n                                ',(null as any));
    this._el_111 = import3.createRenderElement(this.renderer,this._el_109,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_112 = this.renderer.createText(this._el_111,'в своем репозитории зайти в настройки',(null as any));
    this._text_113 = this.renderer.createText(this._el_109,'\n                                ',(null as any));
    this._el_114 = import3.createRenderElement(this.renderer,this._el_109,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_115 = this.renderer.createText(this._el_114,'выбрать пункт add Webhooks',(null as any));
    this._text_116 = this.renderer.createText(this._el_109,'\n                                ',(null as any));
    this._el_117 = import3.createRenderElement(this.renderer,this._el_109,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_118 = this.renderer.createText(this._el_117,'в поле Payload url вставить http://gitblog.pythonanywhere.com/`git_username`/`git_repo_name`/api/web_hook, где git_username это имя вашего аккаунта GitHub, а git_repo_name - репозитория',(null as any));
    this._text_119 = this.renderer.createText(this._el_109,'\n                                ',(null as any));
    this._el_120 = import3.createRenderElement(this.renderer,this._el_109,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_121 = this.renderer.createText(this._el_120,'вcontent type выбрать application/json',(null as any));
    this._text_122 = this.renderer.createText(this._el_109,'\n                                ',(null as any));
    this._el_123 = import3.createRenderElement(this.renderer,this._el_109,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_124 = this.renderer.createText(this._el_123,'Just the push event и Active должны быть отмечены',(null as any));
    this._text_125 = this.renderer.createText(this._el_109,'\n                                ',(null as any));
    this._el_126 = import3.createRenderElement(this.renderer,this._el_109,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_127 = this.renderer.createText(this._el_126,'финальный аккорд - Add Webhook',(null as any));
    this._text_128 = this.renderer.createText(this._el_109,'\n                                ',(null as any));
    this._el_129 = import3.createRenderElement(this.renderer,this._el_109,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_130 = this.renderer.createText(this._el_129,'или обновлять блог с помощью кнопки Update',(null as any));
    this._text_131 = this.renderer.createText(this._el_109,'\n                            ',(null as any));
    this._text_132 = this.renderer.createText(this._el_107,'\n\n                        ',(null as any));
    this._text_133 = this.renderer.createText(this._el_105,'\n                        ',(null as any));
    this._el_134 = import3.createRenderElement(this.renderer,this._el_105,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_135 = this.renderer.createText(this._el_134,'или обновлять блог с помощью кнопки Update',(null as any));
    this._text_136 = this.renderer.createText(this._el_105,'\n                    ',(null as any));
    this._text_137 = this.renderer.createText(this._el_94,'\n\n                ',(null as any));
    this._text_138 = this.renderer.createText(this._el_92,'\n            ',(null as any));
    this._text_139 = this.renderer.createText(this._el_83,'\n        ',(null as any));
    this._text_140 = this.renderer.createText(this._el_41,'\n\n        ',(null as any));
    this._el_141 = import3.createRenderElement(this.renderer,this._el_41,'div',new import3.InlineArray2(2,'class','panel panel-default'),(null as any));
    this._text_142 = this.renderer.createText(this._el_141,'\n            ',(null as any));
    this._el_143 = import3.createRenderElement(this.renderer,this._el_141,'div',new import3.InlineArray2(2,'class','panel-heading'),(null as any));
    this._text_144 = this.renderer.createText(this._el_143,'\n                ',(null as any));
    this._el_145 = import3.createRenderElement(this.renderer,this._el_143,'h4',new import3.InlineArray2(2,'class','panel-title'),(null as any));
    this._el_146 = import3.createRenderElement(this.renderer,this._el_145,'a',new import3.InlineArray4(4,'data-parent','#accordion1','data-toggle','collapse'),(null as any));
    this._text_147 = this.renderer.createText(this._el_146,'\n                    Почему недоступны комментарии\n                ',(null as any));
    this._text_148 = this.renderer.createText(this._el_143,'\n            ',(null as any));
    this._text_149 = this.renderer.createText(this._el_141,'\n            ',(null as any));
    this._el_150 = import3.createRenderElement(this.renderer,this._el_141,'div',new import3.InlineArray2(2,'class','panel-collapse collapse'),(null as any));
    this._text_151 = this.renderer.createText(this._el_150,'\n                ',(null as any));
    this._el_152 = import3.createRenderElement(this.renderer,this._el_150,'div',new import3.InlineArray2(2,'class','panel-body'),(null as any));
    this._text_153 = this.renderer.createText(this._el_152,'\n                    В форкнутом репозиторие нет возможности оставлять комментарии. ',(null as any));
    this._el_154 = import3.createRenderElement(this.renderer,this._el_152,'br',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_155 = this.renderer.createText(this._el_152,' Необходимо использовать свой репозиторий\n\n                ',(null as any));
    this._text_156 = this.renderer.createText(this._el_150,'\n            ',(null as any));
    this._text_157 = this.renderer.createText(this._el_141,'\n        ',(null as any));
    this._text_158 = this.renderer.createText(this._el_41,'\n\n    ',(null as any));
    this._text_159 = this.renderer.createText(this._el_2,'\n',(null as any));
    this._text_160 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_26,new import3.InlineArray4(4,'submit',(null as any),'reset',(null as any)),this.eventHandler(this.handleEvent_26));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_45,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_45));
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_85,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_85));
    var disposable_3:Function = import3.subscribeToRenderElement(this,this._el_143,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_143));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._text_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._text_32,
      this._anchor_33,
      this._text_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._el_45,
      this._text_46,
      this._el_47,
      this._el_48,
      this._text_49,
      this._text_50,
      this._text_51,
      this._el_52,
      this._text_53,
      this._el_54,
      this._text_55,
      this._el_56,
      this._text_57,
      this._el_58,
      this._text_59,
      this._el_60,
      this._text_61,
      this._el_62,
      this._text_63,
      this._text_64,
      this._text_65,
      this._el_66,
      this._text_67,
      this._el_68,
      this._text_69,
      this._text_70,
      this._el_71,
      this._text_72,
      this._text_73,
      this._el_74,
      this._text_75,
      this._el_76,
      this._text_77,
      this._text_78,
      this._text_79,
      this._text_80,
      this._text_81,
      this._text_82,
      this._el_83,
      this._text_84,
      this._el_85,
      this._text_86,
      this._el_87,
      this._el_88,
      this._text_89,
      this._text_90,
      this._text_91,
      this._el_92,
      this._text_93,
      this._el_94,
      this._text_95,
      this._el_96,
      this._text_97,
      this._el_98,
      this._text_99,
      this._el_100,
      this._text_101,
      this._text_102,
      this._el_103,
      this._text_104,
      this._el_105,
      this._text_106,
      this._el_107,
      this._text_108,
      this._el_109,
      this._text_110,
      this._el_111,
      this._text_112,
      this._text_113,
      this._el_114,
      this._text_115,
      this._text_116,
      this._el_117,
      this._text_118,
      this._text_119,
      this._el_120,
      this._text_121,
      this._text_122,
      this._el_123,
      this._text_124,
      this._text_125,
      this._el_126,
      this._text_127,
      this._text_128,
      this._el_129,
      this._text_130,
      this._text_131,
      this._text_132,
      this._text_133,
      this._el_134,
      this._text_135,
      this._text_136,
      this._text_137,
      this._text_138,
      this._text_139,
      this._text_140,
      this._el_141,
      this._text_142,
      this._el_143,
      this._text_144,
      this._el_145,
      this._el_146,
      this._text_147,
      this._text_148,
      this._text_149,
      this._el_150,
      this._text_151,
      this._el_152,
      this._text_153,
      this._el_154,
      this._text_155,
      this._text_156,
      this._text_157,
      this._text_158,
      this._text_159,
      this._text_160
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import17.AuthProfileComponent) && (0 === requestNodeIndex))) { return this._AuthProfileComponent_0_3.context; }
    if (((token === import27.TemplateRef) && (33 === requestNodeIndex))) { return this._TemplateRef_33_5; }
    if (((token === import28.NgIf) && (33 === requestNodeIndex))) { return this._NgIf_33_6.context; }
    if (((token === import29.NgForm) && ((26 <= requestNodeIndex) && (requestNodeIndex <= 34)))) { return this._NgForm_26_3.context; }
    if (((token === import30.ControlContainer) && ((26 <= requestNodeIndex) && (requestNodeIndex <= 34)))) { return this._ControlContainer_26_4; }
    if (((token === import31.NgControlStatusGroup) && ((26 <= requestNodeIndex) && (requestNodeIndex <= 34)))) { return this._NgControlStatusGroup_26_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_169:any = this.context.faq.state;
    if (import3.checkBinding(throwOnChange,this._expr_169,currVal_169)) {
      var animationTransition_start:any = this.componentType.animations['start'](this,this._el_2,((this._expr_169 == import22.UNINITIALIZED)? 'void': this._expr_169),((currVal_169 == import22.UNINITIALIZED)? 'void': currVal_169));
      this._expr_169 = currVal_169;
    }
    this._AuthProfileComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this._NgForm_26_3.ngDoCheck(this,this._el_26,throwOnChange);
    this._NgControlStatusGroup_26_5.ngDoCheck(this,this._el_26,throwOnChange);
    const currVal_33_0_0:boolean = !this._AuthProfileComponent_0_3.context.logged;
    this._NgIf_33_6.check_ngIf(currVal_33_0_0,throwOnChange,false);
    this._NgIf_33_6.ngDoCheck(this,this._anchor_33,throwOnChange);
    this._vc_33.detectChangesInNestedViews(throwOnChange);
    this._NgControlStatusGroup_26_5.checkHost(this,this,this._el_26,throwOnChange);
    const currVal_170:boolean = !this._AuthProfileComponent_0_3.context.logged;
    if (import3.checkBinding(throwOnChange,this._expr_170,currVal_170)) {
      this.renderer.setElementProperty(this._el_28,'disabled',currVal_170);
      this._expr_170 = currVal_170;
    }
    const currVal_171:boolean = !this._AuthProfileComponent_0_3.context.logged;
    if (import3.checkBinding(throwOnChange,this._expr_171,currVal_171)) {
      this.renderer.setElementProperty(this._el_30,'disabled',currVal_171);
      this._expr_171 = currVal_171;
    }
    const currVal_172:any = this.context.faq.friends;
    if (import3.checkBinding(throwOnChange,this._expr_172,currVal_172)) {
      this.renderer.setElementClass(this._el_52,'in',currVal_172);
      this._expr_172 = currVal_172;
    }
    const currVal_173:any = this.context.faq.github;
    if (import3.checkBinding(throwOnChange,this._expr_173,currVal_173)) {
      this.renderer.setElementClass(this._el_92,'in',currVal_173);
      this._expr_173 = currVal_173;
    }
    const currVal_174:any = this.context.faq.comments;
    if (import3.checkBinding(throwOnChange,this._expr_174,currVal_174)) {
      this.renderer.setElementClass(this._el_150,'in',currVal_174);
      this._expr_174 = currVal_174;
    }
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this._vc_33.destroyNestedViews();
    this.compView_0.destroy();
    this._NgForm_26_3.ngOnDestroy();
  }
  detachInternal():void {
    var animationTransition_start:any = this.componentType.animations['start'](this,this._el_2,this._expr_169,'void');
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 33)) { return new View_StartComponent1(this.viewUtils,this,33,this._anchor_33,this._vc_33); }
    return (null as any);
  }
  handleEvent_26(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._NgForm_26_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'submit')) {
      const pd_sub_0:any = ((<any>this.context.go(this._AuthProfileComponent_0_3.context.login,this._el_28)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_45(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>(this.context.faq.friends = !this.context.faq.friends)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_85(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>(this.context.faq.github = !this.context.faq.github)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_143(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>(this.context.faq.comments = !this.context.faq.comments)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}