/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['input[_ngcontent-%COMP%] {\n  max-width: 50%;\n}\nspan[_ngcontent-%COMP%] {\n  color: #d53f17;\n}\nh4[_ngcontent-%COMP%] {\n  cursor: pointer;\n}\n.panel-title[_ngcontent-%COMP%] {\n  font-size: 100%;\n}'];