/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../../components/controls/controls.component';
import * as import1 from '@angular/core/src/change_detection/change_detection_util';
import * as import2 from '@angular/core/src/linker/view';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/render/api';
import * as import5 from '@angular/core/src/metadata/view';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/constants';
import * as import8 from '@angular/core/src/linker/component_factory';
import * as import9 from '@angular/router/src/router';
import * as import10 from '@angular/router/src/router_state';
import * as import11 from '../../../../../services/http.service';
import * as import12 from './controls.component.scss.shim.ngstyle';
import * as import13 from '@angular/core/src/animation/animation_transition';
import * as import14 from '@angular/core/src/animation/animation_sequence_player';
import * as import15 from '@angular/core/src/animation/animation_styles';
import * as import16 from '@angular/core/src/animation/animation_style_util';
import * as import17 from '@angular/core/src/animation/animation_keyframe';
import * as import18 from '@angular/core/src/animation/animation_player';
import * as import19 from '@angular/core/src/linker/view_container';
import * as import20 from '../../../../node_modules/@angular/router/src/directives/router_link.ngfactory';
import * as import21 from '../../../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import22 from '../../../../../components/popup/popup.component';
import * as import23 from '../popup/popup.component.ngfactory';
import * as import24 from '@angular/common/src/location/location_strategy';
import * as import25 from '@angular/core/src/linker/template_ref';
import * as import26 from '@angular/router/src/directives/router_link';
import * as import27 from '@angular/common/src/directives/ng_if';
export class Wrapper_ControlsComponent {
  /*private*/ _eventHandler:Function;
  context:import0.ControlsComponent;
  /*private*/ _changed:boolean;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  constructor(p0:any,p1:any,p2:any) {
    this._changed = false;
    this.context = new import0.ControlsComponent(p0,p1,p2);
    this._expr_0 = import1.UNINITIALIZED;
    this._expr_1 = import1.UNINITIALIZED;
  }
  ngOnDetach(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  check_post(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_0,currValue))) {
      this._changed = true;
      this.context.post = currValue;
      this._expr_0 = currValue;
    }
  }
  check_owner(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_1,currValue))) {
      this._changed = true;
      this.context.owner = currValue;
      this._expr_1 = currValue;
    }
  }
  ngDoCheck(view:import2.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import2.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_ControlsComponent_Host:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.None,([] as any[]),{});
class View_ControlsComponent_Host0 extends import2.AppView<any> {
  _el_0:any;
  compView_0:import2.AppView<import0.ControlsComponent>;
  _ControlsComponent_0_3:Wrapper_ControlsComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_ControlsComponent_Host0,renderType_ControlsComponent_Host,import6.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'controls',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_ControlsComponent0(this.viewUtils,this,0,this._el_0);
    this._ControlsComponent_0_3 = new Wrapper_ControlsComponent(this.injectorGet(import9.Router,this.parentIndex),this.injectorGet(import10.ActivatedRoute,this.parentIndex),this.injectorGet(import11.HttpService,this.parentIndex));
    this.compView_0.create(this._ControlsComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import8.ComponentRef_<any>(0,this,this._el_0,this._ControlsComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.ControlsComponent) && (0 === requestNodeIndex))) { return this._ControlsComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._ControlsComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const ControlsComponentNgFactory:import8.ComponentFactory<import0.ControlsComponent> = new import8.ComponentFactory<import0.ControlsComponent>('controls',View_ControlsComponent_Host0,import0.ControlsComponent);
const styles_ControlsComponent:any[] = [import12.styles];
var ControlsComponent_controls_states:any = {
  'in': {'opacity': '1'},
  '*': {},
  'void': {}
}
;
function ControlsComponent_controls_factory(view:import2.AppView<any>,element:any,currentState:any,nextState:any):import13.AnimationTransition {
  var previousPlayers:any = view.animationContext.getAnimationPlayers(element,((nextState == 'void')? (null as any): 'controls'));
  var collectedStyles:any = {};
  var player:any = (null as any);
  var totalTime:any = 0;
  var defaultStateStyles:any = ControlsComponent_controls_states['*'];
  var startStateStyles:any = ControlsComponent_controls_states[currentState];
  if ((startStateStyles == (null as any))) { (startStateStyles = defaultStateStyles); }
  var endStateStyles:any = ControlsComponent_controls_states[nextState];
  if ((endStateStyles == (null as any))) { (endStateStyles = defaultStateStyles); }
  if (((player == (null as any)) && ((currentState == 'void') && true))) {
      player = new import14.AnimationSequencePlayer([view.renderer.animate(element,new import15.AnimationStyles(import16.collectAndResolveStyles(collectedStyles,[
        startStateStyles,
        {'opacity': '0'}
      ]
      )),import16.balanceAnimationKeyframes(collectedStyles,endStateStyles,[
        new import17.AnimationKeyframe(0,new import15.AnimationStyles(import16.collectAndResolveStyles(collectedStyles,[{}]))),
        new import17.AnimationKeyframe(1,new import15.AnimationStyles(import16.collectAndResolveStyles(collectedStyles,[{}])))
      ]
    ),200,0,(null as any),previousPlayers)]);
    totalTime = 200;
  }
  if (((player == (null as any)) && (true && (nextState == 'void')))) {
      player = new import14.AnimationSequencePlayer([view.renderer.animate(element,new import15.AnimationStyles(import16.collectAndResolveStyles(collectedStyles,[startStateStyles])),[
        new import17.AnimationKeyframe(0,new import15.AnimationStyles(import16.collectAndResolveStyles(collectedStyles,[{'opacity': 'true'}]))),
        new import17.AnimationKeyframe(1,new import15.AnimationStyles(import16.collectAndResolveStyles(collectedStyles,[{'opacity': '0'}])))
      ]
    ,300,0,(null as any),previousPlayers)]);
    totalTime = 300;
  }
  if ((player == (null as any))) { (player = new import18.NoOpAnimationPlayer()); }
  player.onDone(():void => {
    player.destroy();
    import16.renderStyles(element,view.renderer,import16.prepareFinalAnimationStyles(startStateStyles,endStateStyles));
  });
  new import14.AnimationSequencePlayer(previousPlayers).destroy();
  import16.renderStyles(element,view.renderer,import16.clearStyles(startStateStyles));
  view.animationContext.queueAnimation(element,'controls',player);
  return new import13.AnimationTransition(player,currentState,nextState,totalTime);
}
class View_ControlsComponent1 extends import2.AppView<any> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import19.ViewContainer) {
    super(View_ControlsComponent1,renderType_ControlsComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_2 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'button',new import3.InlineArray2(2,'class','btn btn-danger'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'Remove blog',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_0));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),[disposable_0]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2:any = this.parentView.context.post;
    if (import3.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_0,'hidden',currVal_2);
      this._expr_2 = currVal_2;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.deleteBlog()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
var renderType_ControlsComponent:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.Emulated,styles_ControlsComponent,{'controls': ControlsComponent_controls_factory});
export class View_ControlsComponent0 extends import2.AppView<import0.ControlsComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _RouterLinkWithHref_2_3:import20.Wrapper_RouterLinkWithHref;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _RouterLinkWithHref_5_3:import20.Wrapper_RouterLinkWithHref;
  _text_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _anchor_11:any;
  /*private*/ _vc_11:import19.ViewContainer;
  _TemplateRef_11_5:any;
  _NgIf_11_6:import21.Wrapper_NgIf;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  compView_14:import2.AppView<import22.PopupComponent>;
  _PopupComponent_14_3:import23.Wrapper_PopupComponent;
  _text_15:any;
  /*private*/ _expr_23:any;
  _arr_24:any;
  /*private*/ _expr_25:any;
  _arr_26:any;
  /*private*/ _expr_27:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_ControlsComponent0,renderType_ControlsComponent,import6.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways);
    this._expr_23 = import1.UNINITIALIZED;
    this._arr_24 = import3.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._expr_25 = import1.UNINITIALIZED;
    this._arr_26 = import3.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._expr_27 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','controls'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'a',new import3.InlineArray2(2,'class','btn btn-primary'),(null as any));
    this._RouterLinkWithHref_2_3 = new import20.Wrapper_RouterLinkWithHref(this.parentView.injectorGet(import9.Router,this.parentIndex),this.parentView.injectorGet(import10.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import24.LocationStrategy,this.parentIndex));
    this._text_3 = this.renderer.createText(this._el_2,'Add post',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_0,'a',new import3.InlineArray2(2,'class','btn btn-primary'),(null as any));
    this._RouterLinkWithHref_5_3 = new import20.Wrapper_RouterLinkWithHref(this.parentView.injectorGet(import9.Router,this.parentIndex),this.parentView.injectorGet(import10.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import24.LocationStrategy,this.parentIndex));
    this._text_6 = this.renderer.createText(this._el_5,'Edit post',(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_0,'button',new import3.InlineArray2(2,'class','btn btn-danger'),(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'Remove post',(null as any));
    this._text_10 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._anchor_11 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_11 = new import19.ViewContainer(11,0,this,this._anchor_11);
    this._TemplateRef_11_5 = new import25.TemplateRef_(this,11,this._anchor_11);
    this._NgIf_11_6 = new import21.Wrapper_NgIf(this._vc_11.vcRef,this._TemplateRef_11_5);
    this._text_12 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_13 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,parentRenderNode,'popup',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_14 = new import23.View_PopupComponent0(this.viewUtils,this,14,this._el_14);
    this._PopupComponent_14_3 = new import23.Wrapper_PopupComponent();
    this.compView_14.create(this._PopupComponent_14_3.context);
    this._text_15 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_2,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_2));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_5,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_5));
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_8,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_8));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._anchor_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import26.RouterLinkWithHref) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._RouterLinkWithHref_2_3.context; }
    if (((token === import26.RouterLinkWithHref) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._RouterLinkWithHref_5_3.context; }
    if (((token === import25.TemplateRef) && (11 === requestNodeIndex))) { return this._TemplateRef_11_5; }
    if (((token === import27.NgIf) && (11 === requestNodeIndex))) { return this._NgIf_11_6.context; }
    if (((token === import22.PopupComponent) && (14 === requestNodeIndex))) { return this._PopupComponent_14_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_23:any = this._el_8.state;
    if (import3.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      var animationTransition_controls:any = this.componentType.animations['controls'](this,this._el_0,((this._expr_23 == import1.UNINITIALIZED)? 'void': this._expr_23),((currVal_23 == import1.UNINITIALIZED)? 'void': currVal_23));
      this._expr_23 = currVal_23;
    }
    const currVal_2_0_0:any = this._arr_24(this.context.create);
    this._RouterLinkWithHref_2_3.check_routerLink(currVal_2_0_0,throwOnChange,false);
    this._RouterLinkWithHref_2_3.ngDoCheck(this,this._el_2,throwOnChange);
    const currVal_5_0_0:any = this._arr_26(this.context.edit);
    this._RouterLinkWithHref_5_3.check_routerLink(currVal_5_0_0,throwOnChange,false);
    this._RouterLinkWithHref_5_3.ngDoCheck(this,this._el_5,throwOnChange);
    const currVal_11_0_0:any = (this.context.owner && (this.context.owner.toLowerCase() === this.context.name));
    this._NgIf_11_6.check_ngIf(currVal_11_0_0,throwOnChange,false);
    this._NgIf_11_6.ngDoCheck(this,this._anchor_11,throwOnChange);
    const currVal_14_0_0:any = this.context.hidden;
    this._PopupComponent_14_3.check_hidden(currVal_14_0_0,throwOnChange,false);
    const currVal_14_0_1:any = this.context.popupText;
    this._PopupComponent_14_3.check_popupText(currVal_14_0_1,throwOnChange,false);
    this._PopupComponent_14_3.ngDoCheck(this,this._el_14,throwOnChange);
    this._vc_11.detectChangesInNestedViews(throwOnChange);
    this._RouterLinkWithHref_2_3.checkHost(this,this,this._el_2,throwOnChange);
    const currVal_25:boolean = !this.context.post;
    if (import3.checkBinding(throwOnChange,this._expr_25,currVal_25)) {
      this.renderer.setElementClass(this._el_5,'hidden',currVal_25);
      this._expr_25 = currVal_25;
    }
    this._RouterLinkWithHref_5_3.checkHost(this,this,this._el_5,throwOnChange);
    const currVal_27:boolean = !this.context.post;
    if (import3.checkBinding(throwOnChange,this._expr_27,currVal_27)) {
      this.renderer.setElementClass(this._el_8,'hidden',currVal_27);
      this._expr_27 = currVal_27;
    }
    this.compView_14.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this._vc_11.destroyNestedViews();
    this.compView_14.destroy();
    this._RouterLinkWithHref_2_3.ngOnDestroy();
    this._RouterLinkWithHref_5_3.ngOnDestroy();
  }
  detachInternal():void {
    var animationTransition_controls:any = this.componentType.animations['controls'](this,this._el_0,this._expr_23,'void');
  }
  createEmbeddedViewInternal(nodeIndex:number):import2.AppView<any> {
    if ((nodeIndex == 11)) { return new View_ControlsComponent1(this.viewUtils,this,11,this._anchor_11,this._vc_11); }
    return (null as any);
  }
  handleEvent_2(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_2_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_5(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_5_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_8(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.delete()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}