/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['ul[_ngcontent-%COMP%] {\n    position: absolute;\n    bottom: 1em;\n    left: 50%;\n    transform: translate(-50%);\n\n}\nli.disabled[_ngcontent-%COMP%]   a[_ngcontent-%COMP%] {\n  opacity: 0;\n  transform: scale(0);\n}'];