/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['.search-result[_ngcontent-%COMP%] {\n  position: relative;\n  // left: 7.3em;\n  width: 17em;\n  height: 2.5em;\n  padding: 5px;\n  border-bottom-left-radius: 5px;\n  border-bottom-right-radius: 5px;\n  border: 1px solid #ddd;\n  background-color: #fff;\n  font-size: 1.2em;\n  cursor: pointer;\n  transition: all 0.2s ease;\n\n  &:hover {\n    background-color: #607D8B;\n    color: #eee;\n  }\n}\n\n.search-component[_ngcontent-%COMP%] {\n  height: 5em;\n    margin-top: .5em;\n  padding: 0.5em;\n  border-radius: 5px;\n  background-color: #eee;\n  color: #607D8B;\n}\n\ninput[_ngcontent-%COMP%] {\n  display: inline-block;\n  width: 18.4em;\n  height: 2.2em;\n\n  padding-left: 0.5em;\n  border-radius: 3px;\n  border: none;\n  font-size: 1.1em;\n}\n\nh4[_ngcontent-%COMP%] {\n  // display: inline-block;\n  margin-bottom: .5em;\n  margin-right: .5em;\n}'];