/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['h2[_ngcontent-%COMP%] {\n  color: #1a4379;\n}\n\nsection[_ngcontent-%COMP%] {\n  margin-bottom: 10em;\n}\n\n.text[_ngcontent-%COMP%] {\n  font-size: 1.2em;\n}'];