/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../../components/posts/posts.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '@angular/router/src/router';
import * as import9 from '@angular/router/src/router_state';
import * as import10 from '@angular/common/src/location/location';
import * as import11 from '../../../../../services/http.service';
import * as import12 from './posts.component.scss.shim.ngstyle';
import * as import13 from '@angular/core/src/animation/animation_transition';
import * as import14 from '@angular/core/src/animation/animation_sequence_player';
import * as import15 from '@angular/core/src/animation/animation_styles';
import * as import16 from '@angular/core/src/animation/animation_style_util';
import * as import17 from '@angular/core/src/animation/animation_keyframe';
import * as import18 from '@angular/core/src/animation/animation_player';
import * as import19 from '../../../../../components/controls/controls.component';
import * as import20 from '../controls/controls.component.ngfactory';
import * as import21 from '@angular/core/src/linker/view_container';
import * as import22 from '../../../../node_modules/@angular/router/src/directives/router_link.ngfactory';
import * as import23 from '@angular/common/src/pipes/slice_pipe';
import * as import24 from '@angular/core/src/change_detection/change_detection_util';
import * as import25 from '@angular/common/src/location/location_strategy';
import * as import26 from '@angular/router/src/directives/router_link';
import * as import27 from '../../../../../components/auth/auth-profile.component';
import * as import28 from '../auth/auth-profile.component.ngfactory';
import * as import29 from '../../../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import30 from '../../../../../components/search/search.component';
import * as import31 from '../../../../../services/search.service';
import * as import32 from '../search/search.component.ngfactory';
import * as import33 from '../../../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import34 from '../../../../../components/pagination/pagination.component';
import * as import35 from '../pagination/pagination.component.ngfactory';
import * as import36 from '../../../../../services/auth.service';
import * as import37 from '../../../../../services/user.service';
import * as import38 from '@angular/core/src/linker/template_ref';
import * as import39 from '@angular/http/src/http';
import * as import40 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import41 from '../../../../../services/pager.service';
import * as import42 from '@angular/common/src/directives/ng_if';
import * as import43 from '@angular/common/src/directives/ng_for';
export class Wrapper_PostsComponent {
  /*private*/ _eventHandler:Function;
  context:import0.PostsComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any,p2:any,p3:any) {
    this._changed = false;
    this.context = new import0.PostsComponent(p0,p1,p2,p3);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_PostsComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_PostsComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.PostsComponent>;
  _PostsComponent_0_3:Wrapper_PostsComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_PostsComponent_Host0,renderType_PostsComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'posts',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_PostsComponent0(this.viewUtils,this,0,this._el_0);
    this._PostsComponent_0_3 = new Wrapper_PostsComponent(this.injectorGet(import8.Router,this.parentIndex),this.injectorGet(import9.ActivatedRoute,this.parentIndex),this.injectorGet(import10.Location,this.parentIndex),this.injectorGet(import11.HttpService,this.parentIndex));
    this.compView_0.create(this._PostsComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._PostsComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.PostsComponent) && (0 === requestNodeIndex))) { return this._PostsComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._PostsComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const PostsComponentNgFactory:import7.ComponentFactory<import0.PostsComponent> = new import7.ComponentFactory<import0.PostsComponent>('posts',View_PostsComponent_Host0,import0.PostsComponent);
const styles_PostsComponent:any[] = [import12.styles];
var PostsComponent_posts_states:any = {
  'in': {'opacity': '1'},
  '*': {},
  'void': {}
}
;
function PostsComponent_posts_factory(view:import1.AppView<any>,element:any,currentState:any,nextState:any):import13.AnimationTransition {
  var previousPlayers:any = view.animationContext.getAnimationPlayers(element,((nextState == 'void')? (null as any): 'posts'));
  var collectedStyles:any = {};
  var player:any = (null as any);
  var totalTime:any = 0;
  var defaultStateStyles:any = PostsComponent_posts_states['*'];
  var startStateStyles:any = PostsComponent_posts_states[currentState];
  if ((startStateStyles == (null as any))) { (startStateStyles = defaultStateStyles); }
  var endStateStyles:any = PostsComponent_posts_states[nextState];
  if ((endStateStyles == (null as any))) { (endStateStyles = defaultStateStyles); }
  if (((player == (null as any)) && ((currentState == 'void') && true))) {
      player = new import14.AnimationSequencePlayer([view.renderer.animate(element,new import15.AnimationStyles(import16.collectAndResolveStyles(collectedStyles,[
        startStateStyles,
        {'opacity': '0'}
      ]
      )),import16.balanceAnimationKeyframes(collectedStyles,endStateStyles,[
        new import17.AnimationKeyframe(0,new import15.AnimationStyles(import16.collectAndResolveStyles(collectedStyles,[{}]))),
        new import17.AnimationKeyframe(1,new import15.AnimationStyles(import16.collectAndResolveStyles(collectedStyles,[{}])))
      ]
    ),200,0,(null as any),previousPlayers)]);
    totalTime = 200;
  }
  if (((player == (null as any)) && (true && (nextState == 'void')))) {
      player = new import14.AnimationSequencePlayer([view.renderer.animate(element,new import15.AnimationStyles(import16.collectAndResolveStyles(collectedStyles,[startStateStyles])),[
        new import17.AnimationKeyframe(0,new import15.AnimationStyles(import16.collectAndResolveStyles(collectedStyles,[{'opacity': '0'}]))),
        new import17.AnimationKeyframe(1,new import15.AnimationStyles(import16.collectAndResolveStyles(collectedStyles,[{'opacity': '0'}])))
      ]
    ,0,0,(null as any),previousPlayers)]);
    totalTime = 0;
  }
  if ((player == (null as any))) { (player = new import18.NoOpAnimationPlayer()); }
  player.onDone(():void => {
    player.destroy();
    import16.renderStyles(element,view.renderer,import16.prepareFinalAnimationStyles(startStateStyles,endStateStyles));
  });
  new import14.AnimationSequencePlayer(previousPlayers).destroy();
  import16.renderStyles(element,view.renderer,import16.clearStyles(startStateStyles));
  view.animationContext.queueAnimation(element,'posts',player);
  return new import13.AnimationTransition(player,currentState,nextState,totalTime);
}
class View_PostsComponent1 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import19.ControlsComponent>;
  _ControlsComponent_0_3:import20.Wrapper_ControlsComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import21.ViewContainer) {
    super(View_PostsComponent1,renderType_PostsComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'controls',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_0 = new import20.View_ControlsComponent0(this.viewUtils,this,0,this._el_0);
    this._ControlsComponent_0_3 = new import20.Wrapper_ControlsComponent(this.parentView.injectorGet(import8.Router,this.parentIndex),this.parentView.injectorGet(import9.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import11.HttpService,this.parentIndex));
    this.compView_0.create(this._ControlsComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import19.ControlsComponent) && (0 === requestNodeIndex))) { return this._ControlsComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = (<View_PostsComponent0>this.parentView)._AuthProfileComponent_0_3.context.login;
    this._ControlsComponent_0_3.check_owner(currVal_0_0_0,throwOnChange,false);
    this._ControlsComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_PostsComponent2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _RouterLinkWithHref_4_3:import22.Wrapper_RouterLinkWithHref;
  _text_5:any;
  _text_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  _text_17:any;
  /*private*/ _expr_19:any;
  _arr_20:any;
  /*private*/ _expr_21:any;
  /*private*/ _expr_22:any;
  _pipe_slice_0:import23.SlicePipe;
  /*private*/ _expr_24:any;
  /*private*/ _expr_25:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import21.ViewContainer) {
    super(View_PostsComponent2,renderType_PostsComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_19 = import24.UNINITIALIZED;
    this._arr_20 = import3.pureProxy3((p0:any,p1:any,p2:any):any[] => {
      return [
        p0,
        p1,
        p2
      ]
      ;
    });
    this._expr_21 = import24.UNINITIALIZED;
    this._expr_22 = import24.UNINITIALIZED;
    this._expr_24 = import24.UNINITIALIZED;
    this._expr_25 = import24.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'h3',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'a',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._RouterLinkWithHref_4_3 = new import22.Wrapper_RouterLinkWithHref(this.parentView.parentView.injectorGet(import8.Router,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import9.ActivatedRoute,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import25.LocationStrategy,this.parentView.parentIndex));
    this._text_5 = this.renderer.createText(this._el_4,'',(null as any));
    this._text_6 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_0,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'',(null as any));
    this._text_10 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,this._el_0,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'',(null as any));
    this._text_13 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,this._el_0,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_15 = this.renderer.createText(this._el_14,'',(null as any));
    this._text_16 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._text_17 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_4,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_4));
    this._pipe_slice_0 = new import23.SlicePipe();
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._text_17
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import26.RouterLinkWithHref) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._RouterLinkWithHref_4_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import24.ValueUnwrapper();
    const currVal_19:any = this.context.$implicit.state;
    if (import3.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      var animationTransition_posts:any = this.componentType.animations['posts'](this,this._el_0,((this._expr_19 == import24.UNINITIALIZED)? 'void': this._expr_19),((currVal_19 == import24.UNINITIALIZED)? 'void': currVal_19));
      this._expr_19 = currVal_19;
    }
    const currVal_4_0_0:any = this._arr_20(this.parentView.context.url,'post',this.context.$implicit.id);
    this._RouterLinkWithHref_4_3.check_routerLink(currVal_4_0_0,throwOnChange,false);
    this._RouterLinkWithHref_4_3.ngDoCheck(this,this._el_4,throwOnChange);
    this._RouterLinkWithHref_4_3.checkHost(this,this,this._el_4,throwOnChange);
    const currVal_21:any = import3.inlineInterpolate(1,'',this.context.$implicit.title,'');
    if (import3.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this.renderer.setText(this._text_5,currVal_21);
      this._expr_21 = currVal_21;
    }
    valUnwrapper.reset();
    const currVal_22:any = import3.inlineInterpolate(1,'',valUnwrapper.unwrap(this._pipe_slice_0.transform(this.context.$implicit.date,0,10)),'');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_22,currVal_22))) {
      this.renderer.setText(this._text_9,currVal_22);
      this._expr_22 = currVal_22;
    }
    const currVal_24:any = import3.inlineInterpolate(1,'tags: ',this.context.$implicit.tags,'');
    if (import3.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this.renderer.setText(this._text_12,currVal_24);
      this._expr_24 = currVal_24;
    }
    const currVal_25:any = import3.inlineInterpolate(1,'author: ',(this.context.$implicit.author || 'user'),'');
    if (import3.checkBinding(throwOnChange,this._expr_25,currVal_25)) {
      this.renderer.setText(this._text_15,currVal_25);
      this._expr_25 = currVal_25;
    }
  }
  destroyInternal():void {
    this._RouterLinkWithHref_4_3.ngOnDestroy();
  }
  detachInternal():void {
    var animationTransition_posts:any = this.componentType.animations['posts'](this,this._el_0,this._expr_19,'void');
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_4(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_4_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.savePage()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
var renderType_PostsComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.Emulated,styles_PostsComponent,{'posts': PostsComponent_posts_factory});
export class View_PostsComponent0 extends import1.AppView<import0.PostsComponent> {
  _el_0:any;
  compView_0:import1.AppView<import27.AuthProfileComponent>;
  _AuthProfileComponent_0_3:import28.Wrapper_AuthProfileComponent;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _vc_2:import21.ViewContainer;
  _TemplateRef_2_5:any;
  _NgIf_2_6:import29.Wrapper_NgIf;
  _text_3:any;
  _el_4:any;
  compView_4:import1.AppView<import30.SearchComponent>;
  _SearchService_4_3:import31.SearchService;
  _SearchComponent_4_4:import32.Wrapper_SearchComponent;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _anchor_8:any;
  /*private*/ _vc_8:import21.ViewContainer;
  _TemplateRef_8_5:any;
  _NgFor_8_6:import33.Wrapper_NgFor;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  compView_11:import1.AppView<import34.PaginationComponent>;
  _PaginationComponent_11_3:import35.Wrapper_PaginationComponent;
  _text_12:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_PostsComponent0,renderType_PostsComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'auth-profile',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_0 = new import28.View_AuthProfileComponent0(this.viewUtils,this,0,this._el_0);
    this._AuthProfileComponent_0_3 = new import28.Wrapper_AuthProfileComponent(this.parentView.injectorGet(import8.Router,this.parentIndex),this.parentView.injectorGet(import9.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import10.Location,this.parentIndex),this.parentView.injectorGet(import36.AuthService,this.parentIndex),this.parentView.injectorGet(import37.UserService,this.parentIndex));
    this.compView_0.create(this._AuthProfileComponent_0_3.context);
    this._text_1 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._vc_2 = new import21.ViewContainer(2,(null as any),this,this._anchor_2);
    this._TemplateRef_2_5 = new import38.TemplateRef_(this,2,this._anchor_2);
    this._NgIf_2_6 = new import29.Wrapper_NgIf(this._vc_2.vcRef,this._TemplateRef_2_5);
    this._text_3 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,parentRenderNode,'search',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_4 = new import32.View_SearchComponent0(this.viewUtils,this,4,this._el_4);
    this._SearchService_4_3 = new import31.SearchService(this.parentView.injectorGet(import39.Http,this.parentIndex));
    this._SearchComponent_4_4 = new import32.Wrapper_SearchComponent(this.parentView.injectorGet(import8.Router,this.parentIndex),this.parentView.injectorGet(import9.ActivatedRoute,this.parentIndex),this._SearchService_4_3);
    this.compView_4.create(this._SearchComponent_4_4.context);
    this._text_5 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,parentRenderNode,'section',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'\n    ',(null as any));
    this._anchor_8 = this.renderer.createTemplateAnchor(this._el_6,(null as any));
    this._vc_8 = new import21.ViewContainer(8,6,this,this._anchor_8);
    this._TemplateRef_8_5 = new import38.TemplateRef_(this,8,this._anchor_8);
    this._NgFor_8_6 = new import33.Wrapper_NgFor(this._vc_8.vcRef,this._TemplateRef_8_5,this.parentView.injectorGet(import40.IterableDiffers,this.parentIndex),this.ref);
    this._text_9 = this.renderer.createText(this._el_6,'\n',(null as any));
    this._text_10 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,parentRenderNode,'pagination',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_11 = new import35.View_PaginationComponent0(this.viewUtils,this,11,this._el_11);
    this._PaginationComponent_11_3 = new import35.Wrapper_PaginationComponent(this.parentView.injectorGet(import8.Router,this.parentIndex),this.parentView.injectorGet(import10.Location,this.parentIndex),this.parentView.injectorGet(import9.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import11.HttpService,this.parentIndex),this.parentView.injectorGet(import41.PagerService,this.parentIndex));
    this.compView_11.create(this._PaginationComponent_11_3.context);
    this._text_12 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._anchor_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import27.AuthProfileComponent) && (0 === requestNodeIndex))) { return this._AuthProfileComponent_0_3.context; }
    if (((token === import38.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import42.NgIf) && (2 === requestNodeIndex))) { return this._NgIf_2_6.context; }
    if (((token === import31.SearchService) && (4 === requestNodeIndex))) { return this._SearchService_4_3; }
    if (((token === import30.SearchComponent) && (4 === requestNodeIndex))) { return this._SearchComponent_4_4.context; }
    if (((token === import38.TemplateRef) && (8 === requestNodeIndex))) { return this._TemplateRef_8_5; }
    if (((token === import43.NgFor) && (8 === requestNodeIndex))) { return this._NgFor_8_6.context; }
    if (((token === import34.PaginationComponent) && (11 === requestNodeIndex))) { return this._PaginationComponent_11_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._AuthProfileComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    const currVal_2_0_0:any = this._AuthProfileComponent_0_3.context.canEdit;
    this._NgIf_2_6.check_ngIf(currVal_2_0_0,throwOnChange,false);
    this._NgIf_2_6.ngDoCheck(this,this._anchor_2,throwOnChange);
    this._SearchComponent_4_4.ngDoCheck(this,this._el_4,throwOnChange);
    const currVal_8_0_0:any = this._PaginationComponent_11_3.context.pagedItems;
    this._NgFor_8_6.check_ngForOf(currVal_8_0_0,throwOnChange,false);
    this._NgFor_8_6.ngDoCheck(this,this._anchor_8,throwOnChange);
    this._PaginationComponent_11_3.ngDoCheck(this,this._el_11,throwOnChange);
    this._vc_2.detectChangesInNestedViews(throwOnChange);
    this._vc_8.detectChangesInNestedViews(throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
    this.compView_4.internalDetectChanges(throwOnChange);
    this.compView_11.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this._vc_2.destroyNestedViews();
    this._vc_8.destroyNestedViews();
    this.compView_0.destroy();
    this.compView_4.destroy();
    this.compView_11.destroy();
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 2)) { return new View_PostsComponent1(this.viewUtils,this,2,this._anchor_2,this._vc_2); }
    if ((nodeIndex == 8)) { return new View_PostsComponent2(this.viewUtils,this,8,this._anchor_8,this._vc_8); }
    return (null as any);
  }
}