/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['.loading[_ngcontent-%COMP%] {\n  animation: loading 1s linear infinite;\n}\n\n@keyframes loading {\n  to {\n    transform: rotate(360deg);\n  }\n}'];