/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../../components/comments/comments.component';
import * as import1 from '@angular/core/src/change_detection/change_detection_util';
import * as import2 from '@angular/core/src/linker/view';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/render/api';
import * as import5 from '@angular/core/src/metadata/view';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/constants';
import * as import8 from '@angular/core/src/linker/component_factory';
import * as import9 from '@angular/router/src/router_state';
import * as import10 from '../../../../../services/auth.service';
import * as import11 from '../../../../../services/comments.service';
import * as import12 from './comments.component.scss.shim.ngstyle';
import * as import13 from '@angular/core/src/animation/animation_transition';
import * as import14 from '@angular/core/src/animation/animation_sequence_player';
import * as import15 from '@angular/core/src/animation/animation_styles';
import * as import16 from '@angular/core/src/animation/animation_style_util';
import * as import17 from '@angular/core/src/animation/animation_keyframe';
import * as import18 from '@angular/core/src/animation/animation_player';
import * as import19 from '@angular/core/src/linker/view_container';
import * as import20 from '@angular/core/src/security';
import * as import21 from '../../../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import22 from '@angular/core/src/linker/template_ref';
import * as import23 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import24 from '@angular/common/src/directives/ng_for';
import * as import25 from '../../../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import26 from '../../../../../components/comments/comment-form.component';
import * as import27 from './comment-form.component.ngfactory';
import * as import28 from '@angular/common/src/pipes/date_pipe';
import * as import29 from '../../../../../pipes/markdown.pipe';
import * as import30 from '../../../../../pipes/safe-html.pipe';
import * as import31 from '@angular/core/src/i18n/tokens';
import * as import32 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import33 from '@angular/common/src/directives/ng_if';
export class Wrapper_CommentsComponent {
  /*private*/ _eventHandler:Function;
  context:import0.CommentsComponent;
  /*private*/ _changed:boolean;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  constructor(p0:any,p1:any,p2:any) {
    this._changed = false;
    this.context = new import0.CommentsComponent(p0,p1,p2);
    this._expr_0 = import1.UNINITIALIZED;
    this._expr_1 = import1.UNINITIALIZED;
  }
  ngOnDetach(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  check_postId(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_0,currValue))) {
      this._changed = true;
      this.context.postId = currValue;
      this._expr_0 = currValue;
    }
  }
  check_logged(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_1,currValue))) {
      this._changed = true;
      this.context.logged = currValue;
      this._expr_1 = currValue;
    }
  }
  ngDoCheck(view:import2.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import2.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_CommentsComponent_Host:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.None,([] as any[]),{});
class View_CommentsComponent_Host0 extends import2.AppView<any> {
  _el_0:any;
  compView_0:import2.AppView<import0.CommentsComponent>;
  _CommentsComponent_0_3:Wrapper_CommentsComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_CommentsComponent_Host0,renderType_CommentsComponent_Host,import6.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'comments',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_CommentsComponent0(this.viewUtils,this,0,this._el_0);
    this._CommentsComponent_0_3 = new Wrapper_CommentsComponent(this.injectorGet(import9.ActivatedRoute,this.parentIndex),this.injectorGet(import10.AuthService,this.parentIndex),this.injectorGet(import11.CommentsService,this.parentIndex));
    this.compView_0.create(this._CommentsComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import8.ComponentRef_<any>(0,this,this._el_0,this._CommentsComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.CommentsComponent) && (0 === requestNodeIndex))) { return this._CommentsComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._CommentsComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const CommentsComponentNgFactory:import8.ComponentFactory<import0.CommentsComponent> = new import8.ComponentFactory<import0.CommentsComponent>('comments',View_CommentsComponent_Host0,import0.CommentsComponent);
const styles_CommentsComponent:any[] = [import12.styles];
var CommentsComponent_comment_states:any = {
  'in': {'opacity': '1'},
  '*': {},
  'void': {}
}
;
function CommentsComponent_comment_factory(view:import2.AppView<any>,element:any,currentState:any,nextState:any):import13.AnimationTransition {
  var previousPlayers:any = view.animationContext.getAnimationPlayers(element,((nextState == 'void')? (null as any): 'comment'));
  var collectedStyles:any = {};
  var player:any = (null as any);
  var totalTime:any = 0;
  var defaultStateStyles:any = CommentsComponent_comment_states['*'];
  var startStateStyles:any = CommentsComponent_comment_states[currentState];
  if ((startStateStyles == (null as any))) { (startStateStyles = defaultStateStyles); }
  var endStateStyles:any = CommentsComponent_comment_states[nextState];
  if ((endStateStyles == (null as any))) { (endStateStyles = defaultStateStyles); }
  if (((player == (null as any)) && ((currentState == 'void') && true))) {
      player = new import14.AnimationSequencePlayer([view.renderer.animate(element,new import15.AnimationStyles(import16.collectAndResolveStyles(collectedStyles,[
        startStateStyles,
        {'opacity': '0'}
      ]
      )),import16.balanceAnimationKeyframes(collectedStyles,endStateStyles,[
        new import17.AnimationKeyframe(0,new import15.AnimationStyles(import16.collectAndResolveStyles(collectedStyles,[{}]))),
        new import17.AnimationKeyframe(1,new import15.AnimationStyles(import16.collectAndResolveStyles(collectedStyles,[{}])))
      ]
    ),300,0,(null as any),previousPlayers)]);
    totalTime = 300;
  }
  if (((player == (null as any)) && (true && (nextState == 'void')))) {
      player = new import14.AnimationSequencePlayer([view.renderer.animate(element,new import15.AnimationStyles(import16.collectAndResolveStyles(collectedStyles,[startStateStyles])),[
        new import17.AnimationKeyframe(0,new import15.AnimationStyles(import16.collectAndResolveStyles(collectedStyles,[{'opacity': 'true'}]))),
        new import17.AnimationKeyframe(1,new import15.AnimationStyles(import16.collectAndResolveStyles(collectedStyles,[{'opacity': '0'}])))
      ]
    ,300,0,(null as any),previousPlayers)]);
    totalTime = 300;
  }
  if ((player == (null as any))) { (player = new import18.NoOpAnimationPlayer()); }
  player.onDone(():void => {
    player.destroy();
    import16.renderStyles(element,view.renderer,import16.prepareFinalAnimationStyles(startStateStyles,endStateStyles));
  });
  new import14.AnimationSequencePlayer(previousPlayers).destroy();
  import16.renderStyles(element,view.renderer,import16.clearStyles(startStateStyles));
  view.animationContext.queueAnimation(element,'comment',player);
  return new import13.AnimationTransition(player,currentState,nextState,totalTime);
}
class View_CommentsComponent2 extends import2.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _text_22:any;
  /*private*/ _expr_23:any;
  /*private*/ _expr_24:any;
  /*private*/ _expr_25:any;
  /*private*/ _expr_26:any;
  /*private*/ _expr_27:any;
  /*private*/ _expr_28:any;
  _pipe_date_0_0:any;
  /*private*/ _expr_30:any;
  _pipe_markdown_1_0:any;
  _pipe_safeHtml_2_0:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import19.ViewContainer) {
    super(View_CommentsComponent2,renderType_CommentsComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_23 = import1.UNINITIALIZED;
    this._expr_24 = import1.UNINITIALIZED;
    this._expr_25 = import1.UNINITIALIZED;
    this._expr_26 = import1.UNINITIALIZED;
    this._expr_27 = import1.UNINITIALIZED;
    this._expr_28 = import1.UNINITIALIZED;
    this._expr_30 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'li',new import3.InlineArray2(2,'class','comment'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'a',new import3.InlineArray4(4,'class','pull-left','target','_blank'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n                ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'img',new import3.InlineArray4(4,'alt','avatar','class','avatar'),(null as any));
    this._text_5 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._text_6 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','comment-body'),(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'\n                ',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_7,'div',new import3.InlineArray2(2,'class','comment-heading'),(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'\n                    ',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,this._el_9,'h4',new import3.InlineArray2(2,'class','user'),(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'',(null as any));
    this._text_13 = this.renderer.createText(this._el_9,'\n                    ',(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,this._el_9,'h5',new import3.InlineArray2(2,'class','time'),(null as any));
    this._text_15 = this.renderer.createText(this._el_14,'',(null as any));
    this._text_16 = this.renderer.createText(this._el_9,'\n                    ',(null as any));
    this._el_17 = import3.createRenderElement(this.renderer,this._el_9,'span',new import3.InlineArray2(2,'class','glyphicon glyphicon-trash delete'),(null as any));
    this._text_18 = this.renderer.createText(this._el_9,'\n                ',(null as any));
    this._text_19 = this.renderer.createText(this._el_7,'\n                ',(null as any));
    this._el_20 = import3.createRenderElement(this.renderer,this._el_7,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_21 = this.renderer.createText(this._el_7,'\n            ',(null as any));
    this._text_22 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._pipe_date_0_0 = import3.pureProxy2((<View_CommentsComponent0>this.parentView.parentView)._pipe_date_0.transform.bind((<View_CommentsComponent0>this.parentView.parentView)._pipe_date_0));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_17,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_17));
    this._pipe_markdown_1_0 = import3.pureProxy1((<View_CommentsComponent0>this.parentView.parentView)._pipe_markdown_1.transform.bind((<View_CommentsComponent0>this.parentView.parentView)._pipe_markdown_1));
    this._pipe_safeHtml_2_0 = import3.pureProxy1((<View_CommentsComponent0>this.parentView.parentView)._pipe_safeHtml_2.transform.bind((<View_CommentsComponent0>this.parentView.parentView)._pipe_safeHtml_2));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22
    ]
    ),[disposable_0]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import1.ValueUnwrapper();
    const currVal_24:any = this.context.$implicit.state;
    if (import3.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      var animationTransition_comment:any = this.componentType.animations['comment'](this,this._el_2,((this._expr_24 == import1.UNINITIALIZED)? 'void': this._expr_24),((currVal_24 == import1.UNINITIALIZED)? 'void': currVal_24));
      this._expr_24 = currVal_24;
    }
    const currVal_26:any = this.context.$implicit.state;
    if (import3.checkBinding(throwOnChange,this._expr_26,currVal_26)) {
      var animationTransition_comment:any = this.componentType.animations['comment'](this,this._el_7,((this._expr_26 == import1.UNINITIALIZED)? 'void': this._expr_26),((currVal_26 == import1.UNINITIALIZED)? 'void': currVal_26));
      this._expr_26 = currVal_26;
    }
    const currVal_23:any = (this.parentView.parentView.context.url + this.context.$implicit.user);
    if (import3.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      this.renderer.setElementProperty(this._el_2,'href',this.viewUtils.sanitizer.sanitize(import20.SecurityContext.URL,currVal_23));
      this._expr_23 = currVal_23;
    }
    const currVal_25:any = this.context.$implicit.avatar_url;
    if (import3.checkBinding(throwOnChange,this._expr_25,currVal_25)) {
      this.renderer.setElementProperty(this._el_4,'src',this.viewUtils.sanitizer.sanitize(import20.SecurityContext.URL,currVal_25));
      this._expr_25 = currVal_25;
    }
    const currVal_27:any = import3.inlineInterpolate(1,'',this.context.$implicit.user,'');
    if (import3.checkBinding(throwOnChange,this._expr_27,currVal_27)) {
      this.renderer.setText(this._text_12,currVal_27);
      this._expr_27 = currVal_27;
    }
    valUnwrapper.reset();
    const currVal_28:any = import3.inlineInterpolate(1,'',valUnwrapper.unwrap(import3.castByValue(this._pipe_date_0_0,(<View_CommentsComponent0>this.parentView.parentView)._pipe_date_0.transform)(this.context.$implicit.created_at,'y-MM-dd HH:mm')),'');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_28,currVal_28))) {
      this.renderer.setText(this._text_15,currVal_28);
      this._expr_28 = currVal_28;
    }
    valUnwrapper.reset();
    const currVal_30:any = valUnwrapper.unwrap(import3.castByValue(this._pipe_safeHtml_2_0,(<View_CommentsComponent0>this.parentView.parentView)._pipe_safeHtml_2.transform)(valUnwrapper.unwrap(import3.castByValue(this._pipe_markdown_1_0,(<View_CommentsComponent0>this.parentView.parentView)._pipe_markdown_1.transform)(this.context.$implicit.body))));
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_30,currVal_30))) {
      this.renderer.setElementProperty(this._el_20,'innerHTML',this.viewUtils.sanitizer.sanitize(import20.SecurityContext.HTML,currVal_30));
      this._expr_30 = currVal_30;
    }
  }
  detachInternal():void {
    var animationTransition_comment:any = this.componentType.animations['comment'](this,this._el_2,this._expr_24,'void');
    var animationTransition_comment:any = this.componentType.animations['comment'](this,this._el_7,this._expr_26,'void');
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_17(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.parentView.context.remove(this.context.$implicit)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_CommentsComponent1 extends import2.AppView<any> {
  _el_0:any;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _vc_2:import19.ViewContainer;
  _TemplateRef_2_5:any;
  _NgFor_2_6:import21.Wrapper_NgFor;
  _text_3:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import19.ViewContainer) {
    super(View_CommentsComponent1,renderType_CommentsComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'ul',new import3.InlineArray2(2,'class','comments-list'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_2 = new import19.ViewContainer(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import22.TemplateRef_(this,2,this._anchor_2);
    this._NgFor_2_6 = new import21.Wrapper_NgFor(this._vc_2.vcRef,this._TemplateRef_2_5,this.parentView.parentView.injectorGet(import23.IterableDiffers,this.parentView.parentIndex),this.parentView.ref);
    this._text_3 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import22.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import24.NgFor) && (2 === requestNodeIndex))) { return this._NgFor_2_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2_0_0:any = this.parentView.context.comments;
    this._NgFor_2_6.check_ngForOf(currVal_2_0_0,throwOnChange,false);
    this._NgFor_2_6.ngDoCheck(this,this._anchor_2,throwOnChange);
    this._vc_2.detectChangesInNestedViews(throwOnChange);
  }
  destroyInternal():void {
    this._vc_2.destroyNestedViews();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  createEmbeddedViewInternal(nodeIndex:number):import2.AppView<any> {
    if ((nodeIndex == 2)) { return new View_CommentsComponent2(this.viewUtils,this,2,this._anchor_2,this._vc_2); }
    return (null as any);
  }
}
class View_CommentsComponent3 extends import2.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import19.ViewContainer) {
    super(View_CommentsComponent3,renderType_CommentsComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'No comments. You will be first.',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_CommentsComponent4 extends import2.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import19.ViewContainer) {
    super(View_CommentsComponent4,renderType_CommentsComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'You must be logged in to post a comment.',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
var renderType_CommentsComponent:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.Emulated,styles_CommentsComponent,{'comment': CommentsComponent_comment_factory});
export class View_CommentsComponent0 extends import2.AppView<import0.CommentsComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _anchor_5:any;
  /*private*/ _vc_5:import19.ViewContainer;
  _TemplateRef_5_5:any;
  _NgIf_5_6:import25.Wrapper_NgIf;
  _text_6:any;
  _anchor_7:any;
  /*private*/ _vc_7:import19.ViewContainer;
  _TemplateRef_7_5:any;
  _NgIf_7_6:import25.Wrapper_NgIf;
  _text_8:any;
  _anchor_9:any;
  /*private*/ _vc_9:import19.ViewContainer;
  _TemplateRef_9_5:any;
  _NgIf_9_6:import25.Wrapper_NgIf;
  _text_10:any;
  _el_11:any;
  compView_11:import2.AppView<import26.CommentFormComponent>;
  _CommentFormComponent_11_3:import27.Wrapper_CommentFormComponent;
  _text_12:any;
  _text_13:any;
  /*private*/ _expr_25:any;
  _pipe_date_0:import28.DatePipe;
  _pipe_markdown_1:import29.MarkdownPipe;
  _pipe_safeHtml_2:import30.SafeHtmlPipe;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_CommentsComponent0,renderType_CommentsComponent,import6.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways);
    this._expr_25 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','post-footer'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'h3',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._anchor_5 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_5 = new import19.ViewContainer(5,0,this,this._anchor_5);
    this._TemplateRef_5_5 = new import22.TemplateRef_(this,5,this._anchor_5);
    this._NgIf_5_6 = new import25.Wrapper_NgIf(this._vc_5.vcRef,this._TemplateRef_5_5);
    this._text_6 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._anchor_7 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_7 = new import19.ViewContainer(7,0,this,this._anchor_7);
    this._TemplateRef_7_5 = new import22.TemplateRef_(this,7,this._anchor_7);
    this._NgIf_7_6 = new import25.Wrapper_NgIf(this._vc_7.vcRef,this._TemplateRef_7_5);
    this._text_8 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._anchor_9 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_9 = new import19.ViewContainer(9,0,this,this._anchor_9);
    this._TemplateRef_9_5 = new import22.TemplateRef_(this,9,this._anchor_9);
    this._NgIf_9_6 = new import25.Wrapper_NgIf(this._vc_9.vcRef,this._TemplateRef_9_5);
    this._text_10 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,this._el_0,'comment-from',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_11 = new import27.View_CommentFormComponent0(this.viewUtils,this,11,this._el_11);
    this._CommentFormComponent_11_3 = new import27.Wrapper_CommentFormComponent(this.parentView.injectorGet(import9.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import10.AuthService,this.parentIndex),this.parentView.injectorGet(import11.CommentsService,this.parentIndex));
    this.compView_11.create(this._CommentFormComponent_11_3.context);
    this._text_12 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_13 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._pipe_date_0 = new import28.DatePipe(this.parentView.injectorGet(import31.LOCALE_ID,this.parentIndex));
    this._pipe_markdown_1 = new import29.MarkdownPipe();
    this._pipe_safeHtml_2 = new import30.SafeHtmlPipe(this.parentView.injectorGet(import32.DomSanitizer,this.parentIndex));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_11,new import3.InlineArray2(2,'addComment',(null as any)),this.eventHandler(this.handleEvent_11));
    this._CommentFormComponent_11_3.subscribe(this,this.eventHandler(this.handleEvent_11),true);
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._anchor_5,
      this._text_6,
      this._anchor_7,
      this._text_8,
      this._anchor_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import22.TemplateRef) && (5 === requestNodeIndex))) { return this._TemplateRef_5_5; }
    if (((token === import33.NgIf) && (5 === requestNodeIndex))) { return this._NgIf_5_6.context; }
    if (((token === import22.TemplateRef) && (7 === requestNodeIndex))) { return this._TemplateRef_7_5; }
    if (((token === import33.NgIf) && (7 === requestNodeIndex))) { return this._NgIf_7_6.context; }
    if (((token === import22.TemplateRef) && (9 === requestNodeIndex))) { return this._TemplateRef_9_5; }
    if (((token === import33.NgIf) && (9 === requestNodeIndex))) { return this._NgIf_9_6.context; }
    if (((token === import26.CommentFormComponent) && (11 === requestNodeIndex))) { return this._CommentFormComponent_11_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_5_0_0:any = this.context.comments.length;
    this._NgIf_5_6.check_ngIf(currVal_5_0_0,throwOnChange,false);
    this._NgIf_5_6.ngDoCheck(this,this._anchor_5,throwOnChange);
    const currVal_7_0_0:boolean = !this.context.comments.length;
    this._NgIf_7_6.check_ngIf(currVal_7_0_0,throwOnChange,false);
    this._NgIf_7_6.ngDoCheck(this,this._anchor_7,throwOnChange);
    const currVal_9_0_0:boolean = !this.context.logged;
    this._NgIf_9_6.check_ngIf(currVal_9_0_0,throwOnChange,false);
    this._NgIf_9_6.ngDoCheck(this,this._anchor_9,throwOnChange);
    const currVal_11_0_0:any = this.context.postId;
    this._CommentFormComponent_11_3.check_postId(currVal_11_0_0,throwOnChange,false);
    this._CommentFormComponent_11_3.ngDoCheck(this,this._el_11,throwOnChange);
    this._vc_5.detectChangesInNestedViews(throwOnChange);
    this._vc_7.detectChangesInNestedViews(throwOnChange);
    this._vc_9.detectChangesInNestedViews(throwOnChange);
    const currVal_25:any = import3.inlineInterpolate(1,'Comments (',this.context.comments.length,')');
    if (import3.checkBinding(throwOnChange,this._expr_25,currVal_25)) {
      this.renderer.setText(this._text_3,currVal_25);
      this._expr_25 = currVal_25;
    }
    this.compView_11.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this._vc_5.destroyNestedViews();
    this._vc_7.destroyNestedViews();
    this._vc_9.destroyNestedViews();
    this.compView_11.destroy();
    this._CommentFormComponent_11_3.ngOnDestroy();
  }
  createEmbeddedViewInternal(nodeIndex:number):import2.AppView<any> {
    if ((nodeIndex == 5)) { return new View_CommentsComponent1(this.viewUtils,this,5,this._anchor_5,this._vc_5); }
    if ((nodeIndex == 7)) { return new View_CommentsComponent3(this.viewUtils,this,7,this._anchor_7,this._vc_7); }
    if ((nodeIndex == 9)) { return new View_CommentsComponent4(this.viewUtils,this,9,this._anchor_9,this._vc_9); }
    return (null as any);
  }
  handleEvent_11(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'addComment')) {
      const pd_sub_0:any = ((<any>this.context.addCommentHandler($event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}