/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['.post[_ngcontent-%COMP%] {\n  display: flex;\n  justify-content: center;\n  align-items: center;\n  position: absolute;\n  top: 0;\n  left: 0;\n  right: 0;\n  bottom: 0;\n  margin: auto;\n  max-width: 20em;\n  height: 15em;\n  border: 1px solid #999;\n  background-color: #fff;\n  color: green;\n  z-index: 10;\n  &::before {\n    position: absolute;\n    content: "X";\n    top: 1em;\n    right: 1em;\n    color: red;\n    cursor: pointer;\n\n  }\n}'];