/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../../components/edit-post/edit-post.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '@angular/router/src/router';
import * as import9 from '@angular/common/src/location/location';
import * as import10 from '@angular/router/src/router_state';
import * as import11 from '../../../../../services/http.service';
import * as import12 from './edit-post.component.scss.shim.ngstyle';
import * as import13 from '../../../../node_modules/@angular/forms/src/directives/ng_form.ngfactory';
import * as import14 from '../../../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import15 from '../../../../../components/md-editor/md-editor.component';
import * as import16 from '../md-editor/md-editor.component.ngfactory';
import * as import17 from '@angular/core/src/linker/view_container';
import * as import18 from '@angular/core/src/change_detection/change_detection_util';
import * as import19 from '@angular/forms/src/directives/ng_form';
import * as import20 from '@angular/forms/src/directives/control_container';
import * as import21 from '@angular/forms/src/directives/ng_control_status';
import * as import22 from '../../../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import23 from '../../../../../components/popup/popup.component';
import * as import24 from '../popup/popup.component.ngfactory';
import * as import25 from '@angular/core/src/linker/template_ref';
import * as import26 from '@angular/common/src/directives/ng_if';
export class Wrapper_EditPostComponent {
  /*private*/ _eventHandler:Function;
  context:import0.EditPostComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any,p2:any,p3:any) {
    this._changed = false;
    this.context = new import0.EditPostComponent(p0,p1,p2,p3);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_EditPostComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_EditPostComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.EditPostComponent>;
  _EditPostComponent_0_3:Wrapper_EditPostComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_EditPostComponent_Host0,renderType_EditPostComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'ng-component',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_EditPostComponent0(this.viewUtils,this,0,this._el_0);
    this._EditPostComponent_0_3 = new Wrapper_EditPostComponent(this.injectorGet(import8.Router,this.parentIndex),this.injectorGet(import9.Location,this.parentIndex),this.injectorGet(import10.ActivatedRoute,this.parentIndex),this.injectorGet(import11.HttpService,this.parentIndex));
    this.compView_0.create(this._EditPostComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._EditPostComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.EditPostComponent) && (0 === requestNodeIndex))) { return this._EditPostComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._EditPostComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const EditPostComponentNgFactory:import7.ComponentFactory<import0.EditPostComponent> = new import7.ComponentFactory<import0.EditPostComponent>('ng-component',View_EditPostComponent_Host0,import0.EditPostComponent);
const styles_EditPostComponent:any[] = [import12.styles];
class View_EditPostComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _el_5:any;
  _text_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _el_10:any;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _NgForm_14_3:import13.Wrapper_NgForm;
  _ControlContainer_14_4:any;
  _NgControlStatusGroup_14_5:import14.Wrapper_NgControlStatusGroup;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _text_31:any;
  _el_32:any;
  _text_33:any;
  _el_34:any;
  _text_35:any;
  _text_36:any;
  _el_37:any;
  compView_37:import1.AppView<import15.MdEditorComponent>;
  _MdEditorComponent_37_3:import16.Wrapper_MdEditorComponent;
  _text_38:any;
  _text_39:any;
  _el_40:any;
  _text_41:any;
  _el_42:any;
  _text_43:any;
  _text_44:any;
  _el_45:any;
  _text_46:any;
  _text_47:any;
  _el_48:any;
  _text_49:any;
  _text_50:any;
  _text_51:any;
  _text_52:any;
  _text_53:any;
  /*private*/ _expr_59:any;
  /*private*/ _expr_60:any;
  /*private*/ _expr_61:any;
  /*private*/ _expr_62:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import17.ViewContainer) {
    super(View_EditPostComponent1,renderType_EditPostComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_59 = import18.UNINITIALIZED;
    this._expr_60 = import18.UNINITIALIZED;
    this._expr_61 = import18.UNINITIALIZED;
    this._expr_62 = import18.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','col-md-10 col-md-offset-1'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_4,'b',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'Author:',(null as any));
    this._text_7 = this.renderer.createText(this._el_4,'',(null as any));
    this._text_8 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_2,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_9,'b',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'Date:',(null as any));
    this._text_12 = this.renderer.createText(this._el_9,'',(null as any));
    this._text_13 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,this._el_2,'form',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._NgForm_14_3 = new import13.Wrapper_NgForm((null as any),(null as any));
    this._ControlContainer_14_4 = this._NgForm_14_3.context;
    this._NgControlStatusGroup_14_5 = new import14.Wrapper_NgControlStatusGroup(this._ControlContainer_14_4);
    this._text_15 = this.renderer.createText(this._el_14,'\n            ',(null as any));
    this._el_16 = import3.createRenderElement(this.renderer,this._el_14,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'\n                ',(null as any));
    this._el_18 = import3.createRenderElement(this.renderer,this._el_16,'label',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_19 = this.renderer.createText(this._el_18,'Title:',(null as any));
    this._text_20 = this.renderer.createText(this._el_16,'\n                ',(null as any));
    this._el_21 = import3.createRenderElement(this.renderer,this._el_16,'input',new import3.InlineArray16(10,'class','form-control','name','title','placeholder','Title','required','','type','text'),(null as any));
    this._text_22 = this.renderer.createText(this._el_16,'\n            ',(null as any));
    this._text_23 = this.renderer.createText(this._el_14,'\n            ',(null as any));
    this._el_24 = import3.createRenderElement(this.renderer,this._el_14,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._text_25 = this.renderer.createText(this._el_24,'\n                ',(null as any));
    this._el_26 = import3.createRenderElement(this.renderer,this._el_24,'label',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_27 = this.renderer.createText(this._el_26,'Tags:',(null as any));
    this._text_28 = this.renderer.createText(this._el_24,'\n                ',(null as any));
    this._el_29 = import3.createRenderElement(this.renderer,this._el_24,'input',new import3.InlineArray16(10,'class','form-control','name','tags','placeholder','Tags','required','','type','text'),(null as any));
    this._text_30 = this.renderer.createText(this._el_24,'\n            ',(null as any));
    this._text_31 = this.renderer.createText(this._el_14,'\n            ',(null as any));
    this._el_32 = import3.createRenderElement(this.renderer,this._el_14,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._text_33 = this.renderer.createText(this._el_32,'\n                ',(null as any));
    this._el_34 = import3.createRenderElement(this.renderer,this._el_32,'label',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_35 = this.renderer.createText(this._el_34,'Text:',(null as any));
    this._text_36 = this.renderer.createText(this._el_32,'\n                ',(null as any));
    this._el_37 = import3.createRenderElement(this.renderer,this._el_32,'md-editor',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_37 = new import16.View_MdEditorComponent0(this.viewUtils,this,37,this._el_37);
    this._MdEditorComponent_37_3 = new import16.Wrapper_MdEditorComponent();
    this.compView_37.create(this._MdEditorComponent_37_3.context);
    this._text_38 = this.renderer.createText(this._el_32,'\n            ',(null as any));
    this._text_39 = this.renderer.createText(this._el_14,'\n            ',(null as any));
    this._el_40 = import3.createRenderElement(this.renderer,this._el_14,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._text_41 = this.renderer.createText(this._el_40,'\n                ',(null as any));
    this._el_42 = import3.createRenderElement(this.renderer,this._el_40,'button',new import3.InlineArray4(4,'class','btn btn-primary','type','submit'),(null as any));
    this._text_43 = this.renderer.createText(this._el_42,'Update',(null as any));
    this._text_44 = this.renderer.createText(this._el_40,'\n                ',(null as any));
    this._el_45 = import3.createRenderElement(this.renderer,this._el_40,'button',new import3.InlineArray4(4,'class','btn','type','button'),(null as any));
    this._text_46 = this.renderer.createText(this._el_45,'Cancel',(null as any));
    this._text_47 = this.renderer.createText(this._el_40,'\n                ',(null as any));
    this._el_48 = import3.createRenderElement(this.renderer,this._el_40,'button',new import3.InlineArray4(4,'class','btn','type','button'),(null as any));
    this._text_49 = this.renderer.createText(this._el_48,'Back',(null as any));
    this._text_50 = this.renderer.createText(this._el_40,'\n            ',(null as any));
    this._text_51 = this.renderer.createText(this._el_14,'\n        ',(null as any));
    this._text_52 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_53 = this.renderer.createText(this._el_0,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_14,new import3.InlineArray4(4,'submit',(null as any),'reset',(null as any)),this.eventHandler(this.handleEvent_14));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_45,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_45));
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_48,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_48));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._text_44,
      this._el_45,
      this._text_46,
      this._text_47,
      this._el_48,
      this._text_49,
      this._text_50,
      this._text_51,
      this._text_52,
      this._text_53
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import15.MdEditorComponent) && (37 === requestNodeIndex))) { return this._MdEditorComponent_37_3.context; }
    if (((token === import19.NgForm) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 51)))) { return this._NgForm_14_3.context; }
    if (((token === import20.ControlContainer) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 51)))) { return this._ControlContainer_14_4; }
    if (((token === import21.NgControlStatusGroup) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 51)))) { return this._NgControlStatusGroup_14_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._NgForm_14_3.ngDoCheck(this,this._el_14,throwOnChange);
    this._NgControlStatusGroup_14_5.ngDoCheck(this,this._el_14,throwOnChange);
    const currVal_37_0_0:any = this.parentView.context.post.text_full_strings.trim();
    this._MdEditorComponent_37_3.check_value(currVal_37_0_0,throwOnChange,false);
    this._MdEditorComponent_37_3.ngDoCheck(this,this._el_37,throwOnChange);
    const currVal_59:any = import3.inlineInterpolate(1,' ',this.parentView.context.post.author,'');
    if (import3.checkBinding(throwOnChange,this._expr_59,currVal_59)) {
      this.renderer.setText(this._text_7,currVal_59);
      this._expr_59 = currVal_59;
    }
    const currVal_60:any = import3.inlineInterpolate(1,' ',this.parentView.context.post.date,'');
    if (import3.checkBinding(throwOnChange,this._expr_60,currVal_60)) {
      this.renderer.setText(this._text_12,currVal_60);
      this._expr_60 = currVal_60;
    }
    this._NgControlStatusGroup_14_5.checkHost(this,this,this._el_14,throwOnChange);
    const currVal_61:any = this.parentView.context.post.title;
    if (import3.checkBinding(throwOnChange,this._expr_61,currVal_61)) {
      this.renderer.setElementProperty(this._el_21,'value',currVal_61);
      this._expr_61 = currVal_61;
    }
    const currVal_62:any = this.parentView.context.post.tags;
    if (import3.checkBinding(throwOnChange,this._expr_62,currVal_62)) {
      this.renderer.setElementProperty(this._el_29,'value',currVal_62);
      this._expr_62 = currVal_62;
    }
    this.compView_37.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_37.destroy();
    this._NgForm_14_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_14(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._NgForm_14_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'submit')) {
      const pd_sub_0:any = ((<any>this.parentView.context.save(this._el_21,this._el_29,this._MdEditorComponent_37_3.context)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_45(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.cancel(this._MdEditorComponent_37_3.context)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_48(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.goBack()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
var renderType_EditPostComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.Emulated,styles_EditPostComponent,{});
export class View_EditPostComponent0 extends import1.AppView<import0.EditPostComponent> {
  _el_0:any;
  _text_1:any;
  _text_2:any;
  _anchor_3:any;
  /*private*/ _vc_3:import17.ViewContainer;
  _TemplateRef_3_5:any;
  _NgIf_3_6:import22.Wrapper_NgIf;
  _text_4:any;
  _el_5:any;
  compView_5:import1.AppView<import23.PopupComponent>;
  _PopupComponent_5_3:import24.Wrapper_PopupComponent;
  _text_6:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_EditPostComponent0,renderType_EditPostComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'h1',new import3.InlineArray2(2,'class','text-center'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'Edit post',(null as any));
    this._text_2 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._anchor_3 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._vc_3 = new import17.ViewContainer(3,(null as any),this,this._anchor_3);
    this._TemplateRef_3_5 = new import25.TemplateRef_(this,3,this._anchor_3);
    this._NgIf_3_6 = new import22.Wrapper_NgIf(this._vc_3.vcRef,this._TemplateRef_3_5);
    this._text_4 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,parentRenderNode,'popup',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_5 = new import24.View_PopupComponent0(this.viewUtils,this,5,this._el_5);
    this._PopupComponent_5_3 = new import24.Wrapper_PopupComponent();
    this.compView_5.create(this._PopupComponent_5_3.context);
    this._text_6 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._text_2,
      this._anchor_3,
      this._text_4,
      this._el_5,
      this._text_6
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import25.TemplateRef) && (3 === requestNodeIndex))) { return this._TemplateRef_3_5; }
    if (((token === import26.NgIf) && (3 === requestNodeIndex))) { return this._NgIf_3_6.context; }
    if (((token === import23.PopupComponent) && (5 === requestNodeIndex))) { return this._PopupComponent_5_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_3_0_0:any = this.context.post;
    this._NgIf_3_6.check_ngIf(currVal_3_0_0,throwOnChange,false);
    this._NgIf_3_6.ngDoCheck(this,this._anchor_3,throwOnChange);
    const currVal_5_0_0:any = this.context.hidden;
    this._PopupComponent_5_3.check_hidden(currVal_5_0_0,throwOnChange,false);
    const currVal_5_0_1:any = this.context.popupText;
    this._PopupComponent_5_3.check_popupText(currVal_5_0_1,throwOnChange,false);
    this._PopupComponent_5_3.ngDoCheck(this,this._el_5,throwOnChange);
    this._vc_3.detectChangesInNestedViews(throwOnChange);
    this.compView_5.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this._vc_3.destroyNestedViews();
    this.compView_5.destroy();
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 3)) { return new View_EditPostComponent1(this.viewUtils,this,3,this._anchor_3,this._vc_3); }
    return (null as any);
  }
}