/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../../components/create-post/create-post.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '@angular/router/src/router';
import * as import9 from '@angular/common/src/location/location';
import * as import10 from '@angular/router/src/router_state';
import * as import11 from '../../../../../services/auth.service';
import * as import12 from '../../../../../services/user.service';
import * as import13 from '../../../../../services/http.service';
import * as import14 from './create-post.component.scss.shim.ngstyle';
import * as import15 from '../../../../node_modules/@angular/forms/src/directives/ng_form.ngfactory';
import * as import16 from '../../../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import17 from '../../../../../components/md-editor/md-editor.component';
import * as import18 from '../md-editor/md-editor.component.ngfactory';
import * as import19 from '../../../../../components/popup/popup.component';
import * as import20 from '../popup/popup.component.ngfactory';
import * as import21 from '@angular/core/src/change_detection/change_detection_util';
import * as import22 from '@angular/forms/src/directives/ng_form';
import * as import23 from '@angular/forms/src/directives/control_container';
import * as import24 from '@angular/forms/src/directives/ng_control_status';
export class Wrapper_CreatePostComponent {
  /*private*/ _eventHandler:Function;
  context:import0.CreatePostComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any,p2:any,p3:any,p4:any,p5:any) {
    this._changed = false;
    this.context = new import0.CreatePostComponent(p0,p1,p2,p3,p4,p5);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_CreatePostComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_CreatePostComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.CreatePostComponent>;
  _CreatePostComponent_0_3:Wrapper_CreatePostComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_CreatePostComponent_Host0,renderType_CreatePostComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'ng-component',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_CreatePostComponent0(this.viewUtils,this,0,this._el_0);
    this._CreatePostComponent_0_3 = new Wrapper_CreatePostComponent(this.injectorGet(import8.Router,this.parentIndex),this.injectorGet(import9.Location,this.parentIndex),this.injectorGet(import10.ActivatedRoute,this.parentIndex),this.injectorGet(import11.AuthService,this.parentIndex),this.injectorGet(import12.UserService,this.parentIndex),this.injectorGet(import13.HttpService,this.parentIndex));
    this.compView_0.create(this._CreatePostComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._CreatePostComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.CreatePostComponent) && (0 === requestNodeIndex))) { return this._CreatePostComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._CreatePostComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const CreatePostComponentNgFactory:import7.ComponentFactory<import0.CreatePostComponent> = new import7.ComponentFactory<import0.CreatePostComponent>('ng-component',View_CreatePostComponent_Host0,import0.CreatePostComponent);
const styles_CreatePostComponent:any[] = [import14.styles];
var renderType_CreatePostComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.Emulated,styles_CreatePostComponent,{});
export class View_CreatePostComponent0 extends import1.AppView<import0.CreatePostComponent> {
  _el_0:any;
  _text_1:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _el_13:any;
  _text_14:any;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  _NgForm_17_3:import15.Wrapper_NgForm;
  _ControlContainer_17_4:any;
  _NgControlStatusGroup_17_5:import16.Wrapper_NgControlStatusGroup;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _text_26:any;
  _el_27:any;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _text_31:any;
  _el_32:any;
  _text_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _el_37:any;
  _text_38:any;
  _text_39:any;
  _el_40:any;
  _text_41:any;
  _text_42:any;
  _el_43:any;
  _text_44:any;
  _el_45:any;
  _text_46:any;
  _text_47:any;
  _el_48:any;
  compView_48:import1.AppView<import17.MdEditorComponent>;
  _MdEditorComponent_48_3:import18.Wrapper_MdEditorComponent;
  _text_49:any;
  _text_50:any;
  _el_51:any;
  _text_52:any;
  _el_53:any;
  _text_54:any;
  _text_55:any;
  _el_56:any;
  _text_57:any;
  _text_58:any;
  _text_59:any;
  _text_60:any;
  _text_61:any;
  _text_62:any;
  _el_63:any;
  compView_63:import1.AppView<import19.PopupComponent>;
  _PopupComponent_63_3:import20.Wrapper_PopupComponent;
  _text_64:any;
  /*private*/ _expr_72:any;
  /*private*/ _expr_73:any;
  /*private*/ _expr_74:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_CreatePostComponent0,renderType_CreatePostComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
    this._expr_72 = import21.UNINITIALIZED;
    this._expr_73 = import21.UNINITIALIZED;
    this._expr_74 = import21.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'h1',new import3.InlineArray2(2,'class','text-center'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'Create post',(null as any));
    this._text_2 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_3 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_4 = this.renderer.createText(this._el_3,'\n    ',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_3,'div',new import3.InlineArray2(2,'class','col-md-10 col-md-offset-1'),(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'\n        ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_5,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_7,'b',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'Author:',(null as any));
    this._text_10 = this.renderer.createText(this._el_7,'',(null as any));
    this._text_11 = this.renderer.createText(this._el_5,'\n        ',(null as any));
    this._el_12 = import3.createRenderElement(this.renderer,this._el_5,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_13 = import3.createRenderElement(this.renderer,this._el_12,'b',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_14 = this.renderer.createText(this._el_13,'Date:',(null as any));
    this._text_15 = this.renderer.createText(this._el_12,'',(null as any));
    this._text_16 = this.renderer.createText(this._el_5,'\n        ',(null as any));
    this._el_17 = import3.createRenderElement(this.renderer,this._el_5,'form',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._NgForm_17_3 = new import15.Wrapper_NgForm((null as any),(null as any));
    this._ControlContainer_17_4 = this._NgForm_17_3.context;
    this._NgControlStatusGroup_17_5 = new import16.Wrapper_NgControlStatusGroup(this._ControlContainer_17_4);
    this._text_18 = this.renderer.createText(this._el_17,'\n            ',(null as any));
    this._el_19 = import3.createRenderElement(this.renderer,this._el_17,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._text_20 = this.renderer.createText(this._el_19,'\n                ',(null as any));
    this._el_21 = import3.createRenderElement(this.renderer,this._el_19,'label',new import3.InlineArray2(2,'for','filename'),(null as any));
    this._text_22 = this.renderer.createText(this._el_21,'Filename:',(null as any));
    this._text_23 = this.renderer.createText(this._el_19,'\n                ',(null as any));
    this._el_24 = import3.createRenderElement(this.renderer,this._el_19,'input',new import3.InlineArray16(10,'class','form-control','id','filename','placeholder','Filename','required','','type','text'),(null as any));
    this._text_25 = this.renderer.createText(this._el_19,'\n            ',(null as any));
    this._text_26 = this.renderer.createText(this._el_17,'\n            ',(null as any));
    this._el_27 = import3.createRenderElement(this.renderer,this._el_17,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._text_28 = this.renderer.createText(this._el_27,'\n                ',(null as any));
    this._el_29 = import3.createRenderElement(this.renderer,this._el_27,'label',new import3.InlineArray2(2,'for','title'),(null as any));
    this._text_30 = this.renderer.createText(this._el_29,'Title:',(null as any));
    this._text_31 = this.renderer.createText(this._el_27,'\n                ',(null as any));
    this._el_32 = import3.createRenderElement(this.renderer,this._el_27,'input',new import3.InlineArray16(10,'class','form-control','id','title','placeholder','Title','required','','type','text'),(null as any));
    this._text_33 = this.renderer.createText(this._el_27,'\n            ',(null as any));
    this._text_34 = this.renderer.createText(this._el_17,'\n            ',(null as any));
    this._el_35 = import3.createRenderElement(this.renderer,this._el_17,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._text_36 = this.renderer.createText(this._el_35,'\n                ',(null as any));
    this._el_37 = import3.createRenderElement(this.renderer,this._el_35,'label',new import3.InlineArray2(2,'for','tags'),(null as any));
    this._text_38 = this.renderer.createText(this._el_37,'Tags:',(null as any));
    this._text_39 = this.renderer.createText(this._el_35,'\n                ',(null as any));
    this._el_40 = import3.createRenderElement(this.renderer,this._el_35,'input',new import3.InlineArray16(10,'class','form-control','id','tags','placeholder','Tags','required','','type','text'),(null as any));
    this._text_41 = this.renderer.createText(this._el_35,'\n            ',(null as any));
    this._text_42 = this.renderer.createText(this._el_17,'\n            ',(null as any));
    this._el_43 = import3.createRenderElement(this.renderer,this._el_17,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._text_44 = this.renderer.createText(this._el_43,'\n                ',(null as any));
    this._el_45 = import3.createRenderElement(this.renderer,this._el_43,'label',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_46 = this.renderer.createText(this._el_45,'Text:',(null as any));
    this._text_47 = this.renderer.createText(this._el_43,'\n                ',(null as any));
    this._el_48 = import3.createRenderElement(this.renderer,this._el_43,'md-editor',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_48 = new import18.View_MdEditorComponent0(this.viewUtils,this,48,this._el_48);
    this._MdEditorComponent_48_3 = new import18.Wrapper_MdEditorComponent();
    this.compView_48.create(this._MdEditorComponent_48_3.context);
    this._text_49 = this.renderer.createText(this._el_43,'\n            ',(null as any));
    this._text_50 = this.renderer.createText(this._el_17,'\n            ',(null as any));
    this._el_51 = import3.createRenderElement(this.renderer,this._el_17,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._text_52 = this.renderer.createText(this._el_51,'\n                ',(null as any));
    this._el_53 = import3.createRenderElement(this.renderer,this._el_51,'button',new import3.InlineArray4(4,'class','btn btn-primary','type','submit'),(null as any));
    this._text_54 = this.renderer.createText(this._el_53,'Create',(null as any));
    this._text_55 = this.renderer.createText(this._el_51,'\n                ',(null as any));
    this._el_56 = import3.createRenderElement(this.renderer,this._el_51,'button',new import3.InlineArray4(4,'class','btn','type','button'),(null as any));
    this._text_57 = this.renderer.createText(this._el_56,'Back',(null as any));
    this._text_58 = this.renderer.createText(this._el_51,'\n            ',(null as any));
    this._text_59 = this.renderer.createText(this._el_17,'\n        ',(null as any));
    this._text_60 = this.renderer.createText(this._el_5,'\n    ',(null as any));
    this._text_61 = this.renderer.createText(this._el_3,'\n',(null as any));
    this._text_62 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_63 = import3.createRenderElement(this.renderer,parentRenderNode,'popup',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_63 = new import20.View_PopupComponent0(this.viewUtils,this,63,this._el_63);
    this._PopupComponent_63_3 = new import20.Wrapper_PopupComponent();
    this.compView_63.create(this._PopupComponent_63_3.context);
    this._text_64 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_17,new import3.InlineArray4(4,'submit',(null as any),'reset',(null as any)),this.eventHandler(this.handleEvent_17));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_24,new import3.InlineArray2(2,'change',(null as any)),this.eventHandler(this.handleEvent_24));
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_56,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_56));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._el_45,
      this._text_46,
      this._text_47,
      this._el_48,
      this._text_49,
      this._text_50,
      this._el_51,
      this._text_52,
      this._el_53,
      this._text_54,
      this._text_55,
      this._el_56,
      this._text_57,
      this._text_58,
      this._text_59,
      this._text_60,
      this._text_61,
      this._text_62,
      this._el_63,
      this._text_64
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import17.MdEditorComponent) && (48 === requestNodeIndex))) { return this._MdEditorComponent_48_3.context; }
    if (((token === import22.NgForm) && ((17 <= requestNodeIndex) && (requestNodeIndex <= 59)))) { return this._NgForm_17_3.context; }
    if (((token === import23.ControlContainer) && ((17 <= requestNodeIndex) && (requestNodeIndex <= 59)))) { return this._ControlContainer_17_4; }
    if (((token === import24.NgControlStatusGroup) && ((17 <= requestNodeIndex) && (requestNodeIndex <= 59)))) { return this._NgControlStatusGroup_17_5.context; }
    if (((token === import19.PopupComponent) && (63 === requestNodeIndex))) { return this._PopupComponent_63_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._NgForm_17_3.ngDoCheck(this,this._el_17,throwOnChange);
    this._NgControlStatusGroup_17_5.ngDoCheck(this,this._el_17,throwOnChange);
    this._MdEditorComponent_48_3.ngDoCheck(this,this._el_48,throwOnChange);
    const currVal_63_0_0:any = this.context.hidden;
    this._PopupComponent_63_3.check_hidden(currVal_63_0_0,throwOnChange,false);
    const currVal_63_0_1:any = this.context.popupText;
    this._PopupComponent_63_3.check_popupText(currVal_63_0_1,throwOnChange,false);
    this._PopupComponent_63_3.ngDoCheck(this,this._el_63,throwOnChange);
    const currVal_72:any = import3.inlineInterpolate(1,' ',this.context.author,'');
    if (import3.checkBinding(throwOnChange,this._expr_72,currVal_72)) {
      this.renderer.setText(this._text_10,currVal_72);
      this._expr_72 = currVal_72;
    }
    const currVal_73:any = import3.inlineInterpolate(1,' ',this.context.datetime,'');
    if (import3.checkBinding(throwOnChange,this._expr_73,currVal_73)) {
      this.renderer.setText(this._text_15,currVal_73);
      this._expr_73 = currVal_73;
    }
    this._NgControlStatusGroup_17_5.checkHost(this,this,this._el_17,throwOnChange);
    const currVal_74:boolean = !this._MdEditorComponent_48_3.context.value;
    if (import3.checkBinding(throwOnChange,this._expr_74,currVal_74)) {
      this.renderer.setElementProperty(this._el_53,'disabled',currVal_74);
      this._expr_74 = currVal_74;
    }
    this.compView_48.internalDetectChanges(throwOnChange);
    this.compView_63.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_48.destroy();
    this.compView_63.destroy();
    this._NgForm_17_3.ngOnDestroy();
  }
  handleEvent_17(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._NgForm_17_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'submit')) {
      const pd_sub_0:any = ((<any>this.context.push(this._el_24,this._el_32,this._el_40,this._MdEditorComponent_48_3.context)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_24(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'change')) {
      const pd_sub_0:any = ((<any>this.context.repalceSpace(this._el_24)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_56(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.goBack()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}