/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['.absolute[_ngcontent-%COMP%] {\n  position: absolute;\n  top: 20%;\n    left: 50%;\n    transform: translate(-50%);\n  //   right: 0;\n  //   bottom: 0;\n  //   margin: auto;\n}'];